# Working with stock data, I'm not that surprised my original data isn't "normal".
In this segment, my goals are to work with my previously identified small group of stocks in order to impute missing data from SEC filings, and compute percentage changes between one filing and the next. Perhaps I will find that percentage change numbers achieve a more normal distribution. Otherwise, I will need to use entirely nonparametric methods of machine learning in future steps.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('hf-3-day-prices.csv', parse_dates=['date', 'date_minus1', 'date_plus1'])

### Preliminary work from EDA:
1. Collect "tech stock" tickers with the most complete "revenue" column
2. Drop any completely null columns
3. Drop the "split coefficient" columns, they are always 1 in this group of data

In [3]:
# most complete revenues data
tech_revenues = ['CSCO', 'FB', 'GOOGL', 'HPQ', 'IBM', 'ORCL']
df_tech_rev = df[df['ticker'].isin(tech_revenues)]
# drop completely null columns
df_tech_rev = df_tech_rev.dropna(axis='columns', how='all')
# drop split coefficients
dropcols = ['split_coefficient', 'split_coef_minus1', 'split_coef_plus1']
df_tech_rev = df_tech_rev.drop(dropcols, axis=1)
df_tech_rev.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 199 entries, 713 to 1983
Data columns (total 47 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ticker                            199 non-null    object
 1   date                              199 non-null    datetime64[ns]
 2   commonstocksharesissued           160 non-null    float64
 3   assetscurrent                     199 non-null    float64
 4   accountspayablecurrent            199 non-null    float64
 5   commonstockvalue                  19 non-null     float64
 6   liabilities                       122 non-null    float64
 7   liabilitiesandstockholdersequity  199 non-null    float64
 8   stockholdersequity                199 non-null    float64
 9   earningspersharebasic             199 non-null    float64
 10  netincomeloss                     199 non-null    float64
 11  profitloss                        124 non-null    float64
 12  costofgoodssold                   112 non-null    float64
 13  costsandexpenses                  119 non-null    float64
 14  cash                              20 non-null     float64
 15  preferredstockvalue               7 non-null      float64
 16  depreciation                      139 non-null    float64
 17  operatingexpenses                 78 non-null     float64
 18  revenues                          195 non-null    float64
 19  land                              37 non-null     float64
 20  deferredrevenue                   119 non-null    float64
 21  grossprofit                       119 non-null    float64
 22  sharesissued                      51 non-null     float64
 23  commercialpaper                   79 non-null     float64
 24  costofservices                    151 non-null    float64
 25  debtcurrent                       166 non-null    float64
 26  salariesandwages                  39 non-null     float64
 27  open                              198 non-null    float64
 28  high                              198 non-null    float64
 29  low                               198 non-null    float64
 30  close                             198 non-null    float64
 31  close_adjusted                    198 non-null    float64
 32  volume                            198 non-null    float64
 33  date_minus1                       175 non-null    datetime64[ns]
 34  open_minus1                       175 non-null    float64
 35  high_minus1                       175 non-null    float64
 36  low_minus1                        175 non-null    float64
 37  close_minus1                      175 non-null    float64
 38  close_adj_minus1                  175 non-null    float64
 39  volume_minus1                     175 non-null    float64
 40  date_plus1                        171 non-null    datetime64[ns]
 41  open_plus1                        171 non-null    float64
 42  high_plus1                        171 non-null    float64
 43  low_plus1                         171 non-null    float64
 44  close_plus1                       171 non-null    float64
 45  close_adj_plus1                   171 non-null    float64
 46  volume_plus1                      171 non-null    float64
dtypes: datetime64[ns](3), float64(43), object(1)
memory usage: 74.6+ KB

#### Imputing considerations:
1. There are a bunch of columns with really sparse data. I wouldn't be surprised if only one ticker reports some of these figures.
2. I need to do any imputing within tickers, and be sure to not cross data between one ticker and the next.
3. It seems most logical, although complicated, to me to impute by attempting to fill in data that reflect the slope of the changes between one known point and the next.

In [5]:
sparsecols = ['commonstockvalue', 'cash', 'preferredstockvalue', 'operatingexpenses', 'land', 'sharesissued',
              'commercialpaper', 'salariesandwages']
for col in sparsecols:
    print(col + ': ' + df_tech_rev[df_tech_rev[col].notnull()].ticker.unique())

['commonstockvalue: GOOGL' 'commonstockvalue: ORCL']
['cash: FB']
['preferredstockvalue: FB']
['operatingexpenses: CSCO' 'operatingexpenses: HPQ']
['land: ORCL']
['sharesissued: CSCO' 'sharesissued: GOOGL']
['commercialpaper: CSCO' 'commercialpaper: GOOGL' 'commercialpaper: IBM'
 'commercialpaper: ORCL']
['salariesandwages: CSCO']

#### So, I can probably impute data for tickers that have made some reports, but how will I adjust for companies that don't report?

In [7]:
# credit: https://stackoverflow.com/questions/19124601/pretty-print-an-entire-pandas-series-dataframe
with  pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df_tech_rev[df_tech_rev['ticker'] == 'GOOGL'])

,ticker,date,commonstocksharesissued,assetscurrent,accountspayablecurrent,commonstockvalue,liabilities,liabilitiesandstockholdersequity,stockholdersequity,earningspersharebasic,netincomeloss,profitloss,costofgoodssold,costsandexpenses,cash,preferredstockvalue,depreciation,operatingexpenses,revenues,land,deferredrevenue,grossprofit,sharesissued,commercialpaper,costofservices,debtcurrent,salariesandwages,open,high,low,close,close_adjusted,volume,date_minus1,open_minus1,high_minus1,low_minus1,close_minus1,close_adj_minus1,volume_minus1,date_plus1,open_plus1,high_plus1,low_plus1,close_plus1,close_adj_plus1,volume_plus1
1160,GOOGL,2015-10-29,50990000.0,8.810300e+10,1.549000e+09,51000.0,2.617800e+10,1.442810e+11,1.162410e+11,15.95,8.310000e+08,-208000000.0,NaN,3.968000e+10,NaN,NaN,NaN,NaN,2.399800e+10,NaN,NaN,NaN,687348000.0,2.000000e+09,NaN,3.237000e+09,NaN,736.63,746.790,735.16,744.85,744.85,1825957.0,2015-10-28,733.00,737.37,727.27,736.92,736.92,1980154.0,2015-10-30,745.56,746.31,736.5300,737.39,737.39,1999161.0
1161,GOOGL,2016-02-11,50295000.0,9.011400e+10,1.931000e+09,50000.0,2.617800e+10,1.474610e+11,8.922300e+10,23.11,1.634800e+10,-208000000.0,NaN,5.562900e+10,NaN,NaN,NaN,NaN,3.311200e+10,NaN,NaN,NaN,687348000.0,2.000000e+09,NaN,3.225000e+09,NaN,696.34,712.315,691.19,706.36,706.36,3250206.0,2016-02-10,711.79,723.22,705.39,706.85,706.85,3015733.0,2016-02-12,712.21,716.00,701.5800,706.89,706.89,2326889.0
1162,GOOGL,2016-05-03,49536000.0,9.095500e+10,1.667000e+09,NaN,2.617800e+10,1.497470e+11,-1.891000e+09,6.12,4.207000e+09,-169000000.0,NaN,1.491500e+10,NaN,NaN,NaN,NaN,8.955000e+09,NaN,NaN,NaN,691293000.0,NaN,NaN,3.221000e+09,NaN,712.50,713.370,707.33,708.44,708.44,1931040.0,2016-05-02,711.92,715.41,706.36,714.41,714.41,1673820.0,2016-05-04,706.77,715.05,704.0500,711.37,711.37,1708609.0
1163,GOOGL,2016-08-04,48921000.0,9.423800e+10,1.716000e+09,NaN,2.641300e+10,1.542920e+11,-2.010000e+09,13.23,6.560000e+08,-183000000.0,NaN,3.044700e+10,NaN,NaN,NaN,NaN,1.850600e+10,NaN,NaN,NaN,691293000.0,NaN,NaN,2.219000e+09,NaN,798.24,800.200,793.92,797.25,797.25,1076031.0,2016-08-03,796.47,799.54,793.02,798.92,798.92,1461025.0,2016-08-05,800.11,807.22,797.8100,806.93,806.93,1807271.0
1164,GOOGL,2016-11-03,48105000.0,9.854600e+10,2.175000e+09,NaN,2.584500e+10,1.599480e+11,-1.881000e+09,20.59,1.013000e+09,-137000000.0,NaN,4.713100e+10,NaN,NaN,NaN,NaN,2.841800e+10,NaN,NaN,NaN,691293000.0,NaN,NaN,NaN,NaN,784.50,790.000,778.63,782.19,782.19,2175216.0,2016-11-02,806.76,806.76,785.00,788.42,788.42,2350736.0,2016-11-04,771.30,788.48,771.0043,781.10,781.10,1970603.0
1165,GOOGL,2017-02-03,47437000.0,1.054080e+11,2.041000e+09,NaN,2.846100e+10,1.674970e+11,1.051310e+11,28.32,1.947800e+10,NaN,NaN,6.655600e+10,NaN,NaN,NaN,NaN,3.970400e+10,NaN,NaN,NaN,691293000.0,NaN,NaN,NaN,NaN,823.13,826.130,819.35,820.13,820.13,1528095.0,2017-02-02,815.00,824.56,812.05,818.26,818.26,1689179.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1166,GOOGL,2017-05-02,47164000.0,1.087940e+11,2.306000e+09,NaN,2.780700e+10,1.727560e+11,-2.195000e+09,7.85,-2.500000e+07,NaN,NaN,1.818200e+10,NaN,NaN,NaN,NaN,8.091000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,933.27,942.990,931.00,937.09,937.09,1745453.0,2017-05-01,924.15,935.82,920.80,932.82,932.82,2294856.0,2017-05-03,936.05,950.20,935.2100,948.45,948.45,1792847.0
1167,GOOGL,2017-07-25,47101000.0,1.123860e+11,2.488000e+09,NaN,3.033500e+10,1.786210e+11,-1.630000e+09,12.94,-5.100000e+07,NaN,NaN,4.006000e+10,NaN,NaN,NaN,NaN,1.663600e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,970.70,976.730,963.80,969.03,969.03,5793414.0,2017-07-24,994.10,1006.19,990.27,998.31,998.31,3053176.0,2017-07-26,972.78,973.95,960.2300,965.31,965.31,2166225.0
1168,GOOGL,2017-10-27,47054000.0,1.193450e+11,2.674000e+09,NaN,3.243600e+10,1.895360e+11,-1.189000e+09,22.65,-9.800000e+07,NaN,NaN,6.005000e+10,NaN,NaN,NaN,NaN,2.573300e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1030.99,1063.620,1026.85,1033.67,1033.67,5139945.0,2017-10-26,998.47,1006.51,990.47,991.42,991.42,1827682.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1169,GOOGL,2018-02-06,46972000.0,1.243080e+11,3.137000e+09,51000.0,4.479300e+10,1.972950e+11,1.132470e+11,18.27,1.266200e+10,-208000000.0,NaN,8.470900e+10,NaN,NaN,NaN,NaN,3.604600e+10,NaN,NaN,NaN,694783000.0,1.300000e+09,NaN,1.329000e+09,NaN,1033.98,1087.380,1030.01,1084.43,1084.43,3732527.0,2018-02-05,1100.61,1114.99,1056.74,1062.39,1062.39,3742469.0,2018-02-07,1084.97,1086.53,1054.6200,1055.41,1055.41,2544683.0
1170,GOOGL,2018-04-24,46940000.0,1.237610e+11,3.526000e+09,51000.0,4.611000e+10,2.069350e+11,-4.460000e+08,13.53,-3.900000e+07,-208000000.0,NaN,2.414500e+10,NaN,NaN,NaN,NaN,1.500000e+08,NaN,NaN,NaN,695556000.0,1.300000e+09,NaN,1.329000e+09,NaN,1059.20,1064.490,1012.86,1022.64,1022.64,6411038.0,2018-04-23,1082.98,1088.00,1066.68,1073.81,1073.81,3479496.0,2018-04-25,1029.75,1036.07,1017.0100,1022.99,1022.99,2893047.0
1171,GOOGL,2018-07-24,46891000.0,1.241570e+11,3.369000e+09,51000.0,4.961000e+10,2.116100e+11,-1.588000e+09,18.13,-3.300000e+07,-208000000.0,NaN,5.399500e+10,NaN,NaN,NaN,NaN,2.950000e+08,NaN,NaN,NaN,695556000.0,2.000000e+09,NaN,3.237000e+09,NaN,1271.00,1275.000,1244.14,1258.15,1258.15,5380032.0,2018-07-23,1195.66,1215.10,1192.01,1211.00,1211.00,3272304.0,2018-07-25,1252.62,1278.24,1249.0500,1275.94,1275.94,2575437.0
1172,GOOGL,2018-10-26,46880000.0,1.297020e+11,3.789000e+09,51000.0,5.169800e+10,2.215380e+11,-1.569000e+09,31.34,-6.200000e+07,-208000000.0,NaN,7.942500e+10,NaN,NaN,NaN,NaN,4.410000e+08,NaN,NaN,NaN,695556000.0,2.000000e+09,NaN,3.237000e+09,NaN,1048.33,1117.000,1042.23,1083.75,1083.75,5321883.0,2018-10-25,1080.30,1117.82,1075.55,1103.59,1103.59,3647814.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1173,GOOGL,2019-02-05,46636000.0,1.356760e+11,4.378000e+09,51000.0,5.516400e+10,2.327920e+11,1.348850e+11,44.22,3.073600e+10,-208000000.0,NaN,1.104980e+11,NaN,NaN,NaN,NaN,2.399800e+10,NaN,NaN,NaN,695556000.0,2.000000e+09,NaN,3.237000e+09,NaN,1129.63,1152.770,1123.60,1151.87,1151.87,4114790.0,2019-02-04,1119.01,1142.34,1117.51,1141.42,1141.42,3920591.0,2019-02-06,1149.27,1154.00,1118.3600,1122.89,1122.89,2412820.0

I growl greatly at incomplete reporting. There's a couple columns, in Google's case, where I am tempted to just take the "most common" value (commonstockvalue, and profitloss). Commercialpaper? Debt? I know imputing data is basically guessing, and I'm guessing without much benefit of outside information. Also, how do I automate my guessing so I don't have to look through all this data when it's more than a handful of tickers? I suppose, since this is a handful of tickers, that it's worth doing more looking...

In [8]:
with  pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df_tech_rev[df_tech_rev['ticker'] == 'FB'])

,ticker,date,commonstocksharesissued,assetscurrent,accountspayablecurrent,commonstockvalue,liabilities,liabilitiesandstockholdersequity,stockholdersequity,earningspersharebasic,netincomeloss,profitloss,costofgoodssold,costsandexpenses,cash,preferredstockvalue,depreciation,operatingexpenses,revenues,land,deferredrevenue,grossprofit,sharesissued,commercialpaper,costofservices,debtcurrent,salariesandwages,open,high,low,close,close_adjusted,volume,date_minus1,open_minus1,high_minus1,low_minus1,close_minus1,close_adj_minus1,volume_minus1,date_plus1,open_plus1,high_plus1,low_plus1,close_plus1,close_adj_plus1,volume_plus1
980,FB,2012-07-31,1.170000e+08,4.604000e+09,63000000.0,NaN,1.432000e+09,6.331000e+09,4.899000e+09,-0.08,-3.100000e+07,NaN,NaN,1.927000e+09,1.513000e+09,615000000.0,5.660000e+08,NaN,5.960000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.3700,23.37,21.61,21.7100,21.7100,56179400.0,2012-07-30,23.9950,24.040,23.0300,23.150,23.150,29285900.0,2012-08-01,21.50,21.58,20.840,20.880,20.880,44604400.0
981,FB,2012-10-24,1.800000e+08,1.228500e+10,63000000.0,NaN,1.432000e+09,6.331000e+09,1.417400e+10,-0.02,-3.000000e+06,NaN,NaN,1.371000e+09,1.513000e+09,NaN,5.660000e+08,NaN,5.430000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.1300,24.25,22.85,23.2299,23.2299,228949900.0,2012-10-23,19.2500,19.800,19.1000,19.500,19.500,78381200.0,2012-10-25,23.29,23.31,22.470,22.560,22.560,76142000.0
982,FB,2013-02-01,1.170000e+08,1.126700e+10,63000000.0,NaN,1.432000e+09,6.331000e+09,2.162000e+09,0.02,3.500000e+07,NaN,NaN,9.420000e+08,1.513000e+09,NaN,5.660000e+08,NaN,1.644000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.0100,31.02,29.63,29.7300,29.7300,85856700.0,2013-01-31,29.1500,31.470,28.7400,30.981,30.981,190744900.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
983,FB,2013-05-02,1.671000e+09,1.104200e+10,65000000.0,NaN,3.348000e+09,1.510300e+10,1.182400e+10,0.10,1.560000e+08,NaN,NaN,1.085000e+09,1.166000e+09,NaN,5.660000e+08,NaN,5.220000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0099,29.02,27.98,28.9700,28.9700,104257000.0,2013-05-01,27.8500,27.915,27.3100,27.430,27.430,64567600.0,2013-05-03,29.04,29.07,28.150,28.311,28.311,58506400.0
984,FB,2013-07-25,7.010000e+08,1.142100e+10,65000000.0,NaN,3.348000e+09,1.510300e+10,1.234900e+10,-0.08,-1.260000e+08,NaN,NaN,1.251000e+09,1.020000e+09,NaN,5.660000e+08,NaN,1.124000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.5450,34.88,32.75,34.3590,34.3590,365457900.0,2013-07-24,26.3200,26.530,26.0500,26.510,26.510,82635600.0,2013-07-26,33.77,34.73,33.560,34.010,34.010,136028900.0
985,FB,2013-11-01,7.010000e+08,1.054900e+10,65000000.0,NaN,3.348000e+09,1.510300e+10,1.304800e+10,0.17,2.600000e+08,NaN,NaN,1.280000e+09,8.980000e+08,NaN,5.660000e+08,NaN,1.789000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.8500,52.09,49.72,49.7500,49.7500,95033000.0,2013-10-31,47.1550,52.000,46.5000,50.205,50.205,248809000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
986,FB,2014-01-31,7.010000e+08,1.307000e+10,87000000.0,NaN,3.348000e+09,1.510300e+10,-6.000000e+06,0.52,3.500000e+07,NaN,NaN,5.068000e+09,1.044000e+09,NaN,5.660000e+08,NaN,1.644000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.4700,63.37,60.17,62.5700,62.5700,87794600.0,2014-01-30,62.1200,62.500,60.4600,61.080,61.080,150178900.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
987,FB,2014-04-25,1.970000e+09,1.406000e+10,85000000.0,NaN,2.425000e+09,1.902800e+10,1.673700e+10,0.09,1.440000e+08,NaN,NaN,1.427000e+09,1.044000e+09,NaN,9.230000e+08,NaN,7.770000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.9700,60.01,57.57,57.7100,57.7100,92502000.0,2014-04-24,63.6000,63.650,59.7700,60.870,60.870,138769000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
988,FB,2014-07-24,2.013000e+09,1.555700e+10,146000000.0,NaN,2.425000e+09,2.076900e+10,1.834600e+10,0.31,3.170000e+08,NaN,NaN,2.948000e+09,1.044000e+09,NaN,9.230000e+08,NaN,3.023000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.9600,76.74,74.51,74.9800,74.9800,124006900.0,2014-07-23,69.7400,71.330,69.6100,71.290,71.290,77435900.0,2014-07-25,74.99,75.67,74.662,75.190,75.190,45823100.0
989,FB,2014-10-30,5.640000e+08,1.611500e+10,87000000.0,NaN,2.425000e+09,2.418800e+10,1.547000e+10,0.40,6.320000e+08,NaN,NaN,4.754000e+09,1.344000e+09,NaN,9.230000e+08,NaN,4.758000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.0500,75.35,72.90,74.1100,74.1100,83269554.0,2014-10-29,75.4500,76.880,74.7800,75.860,75.860,106119520.0,2014-10-31,74.93,75.70,74.450,74.990,74.990,44544325.0
990,FB,2015-01-29,5.627922e+08,1.367000e+10,176000000.0,NaN,4.088000e+09,4.018400e+10,3.609600e+10,1.12,2.940000e+09,NaN,NaN,7.472000e+09,2.162000e+09,NaN,9.230000e+08,NaN,6.817000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.8500,78.02,74.21,78.0000,78.0000,61293468.0,2015-01-28,76.9000,77.638,76.0000,76.240,76.240,53306422.0,2015-01-30,78.00,78.16,75.750,75.910,75.910,42649491.0
991,FB,2015-04-23,5.590000e+08,1.500400e+10,129000000.0,NaN,4.506000e+09,4.200700e+10,3.750100e+10,0.18,1.020000e+08,NaN,NaN,2.610000e+09,2.644000e+09,NaN,1.220000e+09,NaN,1.891000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.1000,85.59,82.41,82.4100,82.4100,73728080.0,2015-04-22,84.3200,84.740,83.6500,84.630,84.630,45547963.0,2015-04-24,82.77,82.94,81.480,81.530,81.530,29660356.0
992,FB,2015-07-31,5.580000e+08,1.695100e+10,139000000.0,NaN,4.678000e+09,4.413000e+10,3.945200e+10,0.44,2.440000e+08,NaN,NaN,5.380000e+09,2.300000e+09,NaN,1.220000e+09,NaN,4.053000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.9500,96.33,93.95,94.0100,94.0100,46509045.0,2015-07-30,94.9100,95.810,91.8000,95.210,95.210,86211323.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
993,FB,2015-11-05,5.580000e+08,1.913900e+10,149000000.0,NaN,5.049000e+09,4.646900e+10,4.142000e+10,0.76,4.220000e+08,NaN,NaN,8.422000e+09,2.687000e+09,NaN,1.220000e+09,NaN,6.388000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.8000,110.65,107.95,108.7600,108.7600,63232861.0,2015-11-04,103.1900,104.140,102.4800,103.940,103.940,43469308.0,2015-11-06,108.04,108.74,105.910,107.095,107.095,35084342.0
994,FB,2016-01-28,5.520000e+08,2.165200e+10,196000000.0,NaN,5.189000e+09,4.940700e+10,4.421800e+10,1.31,3.688000e+09,NaN,NaN,1.170300e+10,NaN,NaN,1.220000e+09,NaN,9.415000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.2000,110.34,104.81,109.1100,109.1100,107475327.0,2016-01-27,97.7900,97.850,94.2300,94.450,94.450,58699359.0,2016-01-29,108.99,112.84,108.840,112.210,112.210,62739548.0
995,FB,2016-04-28,5.490000e+08,2.381200e+10,149000000.0,NaN,4.925000e+09,5.207500e+10,4.715000e+10,0.53,2.910000e+08,NaN,NaN,3.373000e+09,NaN,NaN,1.590000e+09,NaN,2.873000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.5750,120.79,116.23,116.7300,116.7300,87110080.0,2016-04-27,107.9400,108.940,106.3100,108.890,108.890,52213107.0,2016-04-29,116.82,117.84,115.840,117.580,117.580,37140594.0
996,FB,2016-07-28,5.480000e+08,2.701000e+10,130000000.0,NaN,5.356000e+09,5.573900e+10,5.038300e+10,1.25,6.840000e+08,NaN,NaN,7.064000e+09,NaN,NaN,1.590000e+09,NaN,6.457000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,127.5200,128.33,123.63,125.0000,125.0000,78955758.0,2016-07-27,122.4200,125.000,121.5100,123.340,123.340,52654239.0,2016-07-29,124.65,125.84,123.710,123.940,123.940,35058803.0
997,FB,2016-11-03,5.460000e+08,3.032800e+10,260000000.0,NaN,5.559000e+09,5.967400e+10,5.411500e+10,2.07,1.138000e+09,NaN,NaN,1.095300e+10,NaN,NaN,1.590000e+09,NaN,1.028400e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,122.0000,123.28,119.50,120.0000,120.0000,63766259.0,2016-11-02,130.2300,130.230,126.2800,127.170,127.170,50190225.0,2016-11-04,119.59,121.93,119.250,120.750,120.750,30545466.0
998,FB,2017-02-03,5.380000e+08,3.440100e+10,302000000.0,NaN,5.767000e+09,6.496100e+10,2.167000e+10,3.56,1.021700e+10,NaN,NaN,1.521100e+10,NaN,NaN,1.590000e+09,NaN,1.505900e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,131.2400,132.85,130.76,130.9800,130.9800,24804890.0,2017-02-02,133.2200,135.490,130.4000,130.840,130.840,54366447.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
999,FB,2017-05-04,5.340000e+08,3.693000e+10,170000000.0,NaN,6.526000e+09,6.871400e+10,6.218800e+10,1.06,5.670000e+08,NaN,NaN,4.705000e+09,NaN,NaN,NaN,NaN,4.505000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150.1700,151.52,148.72,150.8500,150.8500,36060301.0,2017-05-03,153.6000,153.600,151.3400,151.800,151.800,21755088.0,2017-05-05,151.45,151.63,149.790,150.240,150.240,17051519.0
1000,FB,2017-07-27,5.320000e+08,4.080400e+10,323000000.0,NaN,7.362000e+09,7.384300e+10,6.648100e+10,2.40,1.286000e+09,NaN,NaN,9.624000e+09,NaN,NaN,NaN,NaN,9.779000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174.7000,175.49,167.50,170.4400,170.4400,68065163.0,2017-07-26,166.0100,166.010,164.1000,165.610,165.610,24081060.0,2017-07-28,169.07,173.43,169.050,172.450,172.450,24036502.0
1001,FB,2017-11-02,5.210000e+08,4.420300e+10,383000000.0,NaN,7.790000e+09,7.899800e+10,7.120800e+10,4.02,2.142000e+09,NaN,NaN,1.483000e+10,NaN,NaN,NaN,NaN,1.562400e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.6300,181.94,177.34,178.9200,178.9200,35119841.0,2017-11-01,182.3600,182.900,180.5700,182.660,182.660,28922959.0,2017-11-03,179.29,179.86,176.710,178.920,178.920,17572587.0
1002,FB,2018-02-01,5.090000e+08,4.856300e+10,380000000.0,NaN,1.017700e+10,8.452400e+10,3.399000e+10,5.49,1.593400e+10,NaN,NaN,2.045000e+10,1.513000e+09,615000000.0,2.330000e+09,NaN,2.291900e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188.2200,195.32,187.89,193.0900,193.0900,53608910.0,2018-01-31,188.3700,189.830,185.2200,186.890,186.890,27299152.0,2018-02-02,192.04,194.21,189.980,190.280,190.280,25514560.0
1003,FB,2018-04-26,4.980000e+08,5.041200e+10,593000000.0,NaN,1.132500e+10,8.894500e+10,7.762000e+10,1.72,8.650000e+08,NaN,NaN,6.517000e+09,1.513000e+09,615000000.0,3.680000e+09,NaN,1.196600e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173.2200,176.27,170.80,174.1600,174.1600,77556934.0,2018-04-25,160.1448,161.060,156.1900,159.690,159.690,41083581.0,2018-04-27,176.81,177.10,172.600,173.590,173.590,29773114.0
1004,FB,2018-07-26,4.780000e+08,4.983300e+10,419000000.0,NaN,1.090900e+10,9.029100e+10,7.938200e+10,3.48,1.725000e+09,NaN,NaN,1.388400e+10,1.513000e+09,615000000.0,3.680000e+09,NaN,2.519700e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174.8900,180.13,173.75,176.2600,176.2600,169803668.0,2018-07-25,215.7150,218.620,214.2700,217.500,217.500,64592585.0,2018-07-27,179.87,179.93,173.000,174.890,174.890,60073749.0
1005,FB,2018-10-31,4.710000e+08,4.914700e+10,590000000.0,NaN,1.211000e+10,9.245200e+10,3.876700e+10,5.26,1.523000e+10,NaN,NaN,2.183100e+10,1.513000e+09,615000000.0,3.680000e+09,NaN,3.892400e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,155.0000,156.40,148.96,151.7900,151.7900,60101251.0,2018-10-30,139.9350,146.640,139.7419,146.220,146.220,50528278.0,2018-11-01,151.52,152.75,149.350,151.750,151.750,25640786.0
1006,FB,2019-01-31,4.690000e+08,5.048000e+10,820000000.0,NaN,1.320700e+10,9.733400e+10,4.198100e+10,7.65,2.211200e+10,NaN,NaN,3.092500e+10,1.513000e+09,615000000.0,3.680000e+09,NaN,5.960000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165.6000,171.68,165.00,166.6900,166.6900,77233602.0,2019-01-30,146.2200,150.950,145.6953,150.420,150.420,44613240.0,2019-02-01,165.84,169.10,165.660,165.710,165.710,30806513.0
1007,FB,2019-04-25,4.520000e+08,5.330000e+10,604000000.0,NaN,2.296100e+10,1.094770e+11,4.376400e+10,0.85,2.429000e+09,NaN,NaN,1.176000e+10,1.513000e+09,615000000.0,5.660000e+08,NaN,5.960000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,196.9800,198.48,192.12,193.2600,193.2600,54062549.0,2019-04-24,184.4900,185.140,181.6500,182.580,182.580,37289871.0,2019-04-26,192.50,192.90,189.090,191.490,191.490,22075002.0

In [9]:
with  pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df_tech_rev[df_tech_rev['ticker'] == 'ORCL'])

,ticker,date,commonstocksharesissued,assetscurrent,accountspayablecurrent,commonstockvalue,liabilities,liabilitiesandstockholdersequity,stockholdersequity,earningspersharebasic,netincomeloss,profitloss,costofgoodssold,costsandexpenses,cash,preferredstockvalue,depreciation,operatingexpenses,revenues,land,deferredrevenue,grossprofit,sharesissued,commercialpaper,costofservices,debtcurrent,salariesandwages,open,high,low,close,close_adjusted,volume,date_minus1,open_minus1,high_minus1,low_minus1,close_minus1,close_adj_minus1,volume_minus1,date_plus1,open_plus1,high_plus1,low_plus1,close_plus1,close_adj_plus1,volume_plus1
1945,ORCL,2009-09-21,NaN,1.858100e+10,271000000.0,1.464800e+10,NaN,5.299800e+10,2.614300e+10,0.21,9.452000e+09,1.123500e+10,NaN,3.810000e+09,NaN,NaN,6.400000e+07,NaN,5.331000e+09,868000000.0,6.288000e+09,1.043100e+10,NaN,881000000.0,1.160000e+08,2.500000e+09,NaN,21.560,21.820,21.500,21.570,19.5155,25487400.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2009-09-22,21.590,21.7075,21.350,21.41,19.3708,34159300.0
1946,ORCL,2009-12-22,NaN,2.523500e+10,255000000.0,1.464800e+10,NaN,5.383300e+10,2.753100e+10,0.46,9.452000e+09,1.123500e+10,NaN,7.442000e+09,NaN,NaN,1.230000e+08,NaN,1.093800e+10,868000000.0,6.288000e+09,1.043100e+10,NaN,881000000.0,1.160000e+08,2.500000e+09,NaN,24.510,24.630,24.240,24.460,22.1836,23847200.0,2009-12-21,24.3900,24.570,24.2200,24.4300,22.1564,26935500.0,2009-12-23,24.460,24.7500,24.360,24.73,22.4285,19257800.0
1947,ORCL,2010-03-29,NaN,2.397900e+10,616000000.0,1.464800e+10,NaN,5.938600e+10,2.847600e+10,0.73,9.452000e+09,1.123500e+10,NaN,1.095500e+10,NaN,NaN,1.960000e+08,NaN,1.639100e+10,868000000.0,6.288000e+09,1.043100e+10,NaN,881000000.0,1.160000e+08,2.500000e+09,NaN,25.645,25.850,25.410,25.570,23.2361,28975300.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2010-03-30,25.480,25.5800,25.220,25.54,23.2088,29819400.0
1948,ORCL,2010-07-01,NaN,1.858100e+10,271000000.0,1.464800e+10,NaN,6.157800e+10,2.509000e+10,1.08,6.230000e+09,5.593000e+09,NaN,1.458600e+10,NaN,NaN,2.980000e+08,NaN,2.243000e+10,757000000.0,6.288000e+09,1.043100e+10,NaN,881000000.0,1.160000e+08,2.950000e+09,NaN,21.460,21.680,21.240,21.550,19.6204,38318200.0,2010-06-30,21.6400,21.960,21.3900,21.4600,19.5384,35301600.0,2010-07-02,21.710,22.0300,21.490,21.83,19.8753,31784000.0
1949,ORCL,2010-12-21,NaN,2.700400e+10,775000000.0,1.464800e+10,NaN,6.157800e+10,3.079800e+10,0.52,9.981000e+09,5.593000e+09,NaN,6.993000e+09,NaN,NaN,1.230000e+08,NaN,1.608400e+10,757000000.0,6.288000e+09,1.043100e+10,NaN,881000000.0,1.160000e+08,2.950000e+09,NaN,31.650,32.000,31.590,31.760,29.0318,20002800.0,2010-12-20,31.5400,31.940,31.1100,31.6750,28.9541,33568100.0,2010-12-22,31.680,31.8825,31.560,31.66,28.9404,14019200.0
1950,ORCL,2011-03-29,NaN,2.700400e+10,775000000.0,1.464800e+10,NaN,6.157800e+10,3.079800e+10,0.75,9.981000e+09,5.593000e+09,NaN,1.155300e+10,NaN,NaN,1.960000e+08,NaN,2.484700e+10,757000000.0,6.288000e+09,1.043100e+10,NaN,881000000.0,1.160000e+08,2.950000e+09,NaN,32.400,33.160,32.360,33.160,30.3601,29950300.0,2011-03-28,32.8300,32.890,32.4000,32.5550,29.8062,31399500.0,2011-03-30,33.270,33.4300,33.000,33.05,30.2594,25718200.0
1951,ORCL,2011-06-28,NaN,3.917400e+10,701000000.0,NaN,NaN,7.353500e+10,3.977600e+10,1.69,9.981000e+09,5.593000e+09,NaN,2.358900e+10,NaN,NaN,2.980000e+08,NaN,2.325200e+10,757000000.0,7.118000e+09,1.043100e+10,NaN,881000000.0,1.259000e+09,2.950000e+09,NaN,31.690,32.370,31.370,32.340,29.6619,32746800.0,2011-06-27,30.9800,31.830,30.8600,31.5800,28.9648,29585600.0,2011-06-29,32.400,32.6800,32.210,32.43,29.7445,27305700.0
1952,ORCL,2011-09-23,NaN,3.917400e+10,701000000.0,NaN,NaN,7.353500e+10,3.977600e+10,0.27,9.981000e+09,6.230000e+09,NaN,5.585000e+09,NaN,NaN,9.900000e+07,NaN,8.374000e+09,692000000.0,7.118000e+09,1.043100e+10,NaN,NaN,8.960000e+08,2.950000e+09,NaN,28.100,29.080,27.810,28.900,26.5548,43991700.0,2011-09-22,28.7400,29.030,27.8309,28.3400,26.0402,61371400.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1953,ORCL,2011-12-23,NaN,3.848200e+10,445000000.0,NaN,NaN,7.291000e+10,4.192000e+10,0.43,9.981000e+09,6.230000e+09,NaN,5.681000e+09,NaN,NaN,2.260000e+08,NaN,8.792000e+09,692000000.0,6.360000e+09,1.043100e+10,NaN,NaN,9.290000e+08,2.950000e+09,NaN,25.800,26.080,25.750,26.060,23.9933,32292800.0,2011-12-22,25.8601,25.870,25.3800,25.6900,23.6526,44203700.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1954,ORCL,2012-03-23,NaN,3.753800e+10,442000000.0,NaN,NaN,7.436100e+10,4.287300e+10,0.50,9.981000e+09,6.230000e+09,NaN,5.722000e+09,NaN,NaN,2.830000e+08,NaN,9.039000e+09,692000000.0,6.591000e+09,1.043100e+10,NaN,NaN,9.220000e+08,2.950000e+09,NaN,28.690,28.890,28.520,28.550,26.3441,36696300.0,2012-03-22,29.3300,29.330,28.5600,28.6300,26.4180,59763200.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1955,ORCL,2012-06-26,NaN,4.002300e+10,438000000.0,NaN,NaN,7.832700e+10,4.368800e+10,1.99,9.981000e+09,6.230000e+09,NaN,2.341500e+10,NaN,NaN,3.680000e+08,NaN,3.712100e+10,692000000.0,7.331000e+09,1.043100e+10,NaN,NaN,3.743000e+09,2.950000e+09,NaN,27.630,27.945,27.515,27.830,25.7329,20614200.0,2012-06-25,27.5400,27.750,27.2400,27.6200,25.5387,24918800.0,2012-06-27,27.760,28.4550,27.760,28.17,26.0473,19388200.0
1956,ORCL,2012-09-24,NaN,3.817200e+10,388000000.0,NaN,NaN,7.655800e+10,4.332900e+10,0.36,1.840000e+09,8.547000e+09,NaN,5.691000e+09,NaN,NaN,1.170000e+08,NaN,8.181000e+09,632000000.0,7.331000e+09,1.043100e+10,NaN,NaN,9.360000e+08,1.250000e+09,NaN,32.250,32.440,32.080,32.225,29.8579,18511200.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2012-09-25,32.180,32.2300,31.250,31.30,29.0008,30757800.0
1957,ORCL,2012-12-21,NaN,4.112900e+10,372000000.0,NaN,NaN,7.965700e+10,4.298300e+10,0.43,4.615000e+09,8.547000e+09,NaN,1.092500e+10,NaN,NaN,2.610000e+08,NaN,1.716600e+10,632000000.0,7.331000e+09,1.043100e+10,NaN,NaN,1.814000e+09,2.950000e+09,NaN,33.510,33.920,33.200,33.760,31.5181,45601600.0,2012-12-20,34.0900,34.250,33.9300,33.9398,31.6860,28119900.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1958,ORCL,2013-03-22,NaN,4.068600e+10,361000000.0,NaN,NaN,7.945000e+10,4.334800e+10,0.50,2.498000e+09,8.547000e+09,NaN,5.722000e+09,NaN,NaN,3.500000e+08,NaN,2.623300e+10,632000000.0,7.331000e+09,1.043100e+10,NaN,NaN,9.220000e+08,1.250000e+09,NaN,32.400,32.500,31.640,31.980,29.8563,64333500.0,2013-03-21,32.7800,32.940,32.1800,32.3000,30.1551,132669500.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1959,ORCL,2013-06-26,NaN,4.002300e+10,438000000.0,NaN,NaN,7.832700e+10,4.368800e+10,1.99,9.981000e+09,8.547000e+09,NaN,2.341500e+10,NaN,NaN,4.860000e+08,NaN,1.600300e+10,632000000.0,7.331000e+09,1.043100e+10,NaN,NaN,3.743000e+09,2.950000e+09,NaN,30.190,30.230,29.860,30.140,28.1385,52429800.0,2013-06-25,30.5000,30.530,29.8900,29.9600,27.9704,64051500.0,2013-06-27,30.310,31.1400,30.291,30.45,28.4279,43014900.0
1960,ORCL,2013-09-20,NaN,4.545700e+10,419000000.0,NaN,NaN,8.640600e+10,4.354100e+10,0.48,2.034000e+09,1.095500e+10,NaN,5.499000e+09,NaN,NaN,1.500000e+08,NaN,8.372000e+09,632000000.0,8.871000e+09,1.043100e+10,NaN,NaN,8.060000e+08,1.533000e+09,NaN,33.940,34.130,33.670,34.050,31.9110,53470400.0,2013-09-19,33.6400,34.000,33.2500,33.8900,31.7610,63316300.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1961,ORCL,2013-12-20,NaN,4.425200e+10,419000000.0,NaN,NaN,8.523800e+10,4.464800e+10,0.96,4.744000e+09,1.095500e+10,NaN,1.092500e+10,NaN,NaN,3.020000e+08,NaN,3.987000e+09,632000000.0,7.011000e+09,1.043100e+10,NaN,NaN,9.300000e+08,1.525000e+09,NaN,36.650,36.795,36.370,36.370,34.2084,40783000.0,2013-12-19,35.5200,36.960,35.5000,36.6000,34.4247,62855300.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1962,ORCL,2014-03-20,NaN,4.169200e+10,396000000.0,NaN,NaN,8.181200e+10,4.470700e+10,0.53,2.504000e+09,1.095500e+10,NaN,5.740000e+09,NaN,NaN,4.000000e+08,NaN,6.000000e+08,632000000.0,6.825000e+09,1.043100e+10,NaN,NaN,2.668000e+09,1.516000e+09,NaN,38.500,38.690,38.010,38.370,36.2047,18960200.0,2014-03-19,37.8000,38.960,37.4000,38.5500,36.3745,45154900.0,2014-03-21,38.700,38.8500,37.500,37.50,35.3838,33897900.0
1963,ORCL,2014-06-26,NaN,4.813800e+10,419000000.0,NaN,NaN,8.181200e+10,4.687800e+10,2.29,1.092500e+10,1.095500e+10,NaN,2.249600e+10,NaN,NaN,5.460000e+08,NaN,3.827500e+10,632000000.0,7.430000e+09,1.043100e+10,NaN,NaN,3.182000e+09,1.508000e+09,NaN,40.550,40.550,39.980,40.150,37.9979,16642500.0,2014-06-25,40.7300,40.840,40.3900,40.4600,38.2913,13889400.0,2014-06-27,40.030,40.6600,40.030,40.53,38.3576,15320500.0
1964,ORCL,2014-09-23,NaN,5.819400e+10,423000000.0,NaN,NaN,9.034400e+10,4.735400e+10,0.48,2.191000e+09,1.103700e+10,NaN,5.633000e+09,NaN,NaN,1.600000e+08,NaN,1.266000e+09,632000000.0,7.673000e+09,1.043100e+10,NaN,NaN,6.910000e+08,1.508000e+09,NaN,39.500,39.590,38.800,38.830,36.8565,34253635.0,2014-09-22,39.6800,39.740,39.2400,39.5800,37.5684,24191139.0,2014-09-24,38.770,39.5560,38.570,39.42,37.4165,18884441.0
1965,ORCL,2014-12-19,NaN,4.813800e+10,490000000.0,NaN,NaN,9.830500e+10,4.754300e+10,0.56,2.502000e+09,1.103700e+10,NaN,6.056000e+09,NaN,NaN,3.020000e+08,NaN,9.275000e+09,632000000.0,7.224000e+09,1.043100e+10,NaN,NaN,7.640000e+08,1.508000e+09,NaN,45.100,46.150,44.980,46.000,43.7962,41782191.0,2014-12-18,43.8300,45.370,43.5700,45.3500,43.1773,54491326.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1966,ORCL,2015-03-19,NaN,5.129400e+10,471000000.0,NaN,NaN,9.034400e+10,4.687800e+10,0.57,2.495000e+09,1.103700e+10,NaN,5.944000e+09,NaN,NaN,4.520000e+08,NaN,9.334000e+09,632000000.0,6.878000e+09,1.043100e+10,NaN,NaN,7.240000e+08,1.999000e+09,NaN,44.000,44.490,44.000,44.160,42.1601,15729627.0,2015-03-18,44.3000,44.935,43.3500,44.1300,42.1314,37896791.0,2015-03-20,44.130,44.7300,44.060,44.41,42.3988,20724698.0
1967,ORCL,2015-06-25,NaN,4.812800e+10,471000000.0,NaN,NaN,9.026600e+10,4.866300e+10,2.42,1.095500e+10,1.103700e+10,NaN,2.249600e+10,NaN,NaN,6.080000e+08,NaN,1.680900e+10,632000000.0,7.673000e+09,1.043100e+10,NaN,NaN,2.954000e+09,1.508000e+09,NaN,41.240,41.470,41.055,41.060,39.3384,13547448.0,2015-06-24,41.5400,41.770,41.2000,41.2000,39.4726,17768033.0,2015-06-26,41.100,41.3700,40.970,40.99,39.2714,39685430.0
1968,ORCL,2015-09-18,NaN,6.212200e+10,422000000.0,NaN,NaN,1.097060e+11,4.709700e+10,0.40,2.184000e+09,9.938000e+09,NaN,5.794000e+09,NaN,NaN,2.190000e+08,NaN,1.166000e+09,744000000.0,7.638000e+09,1.043100e+10,NaN,NaN,6.910000e+08,2.000000e+09,NaN,36.290,36.980,36.260,36.380,34.9849,34919765.0,2015-09-17,36.7400,37.670,36.5000,36.7400,35.3311,37298982.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1969,ORCL,2015-12-18,NaN,6.252000e+10,415000000.0,NaN,NaN,1.064830e+11,4.592400e+10,0.57,2.197000e+09,9.938000e+09,NaN,1.183200e+10,NaN,NaN,3.240000e+08,NaN,8.996000e+09,744000000.0,7.461000e+09,1.043100e+10,NaN,NaN,6.900000e+08,1.999000e+09,NaN,36.890,37.080,36.310,36.350,35.0937,28648184.0,2015-12-17,38.0900,38.200,36.5400,36.9300,35.6536,42879939.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1970,ORCL,2016-03-18,NaN,6.252000e+10,410000000.0,NaN,NaN,1.109030e+11,4.587000e+10,0.57,2.142000e+09,9.938000e+09,NaN,1.781700e+10,NaN,NaN,6.430000e+08,NaN,9.327000e+09,744000000.0,7.638000e+09,1.043100e+10,NaN,NaN,6.570000e+08,1.999000e+09,NaN,40.870,41.490,40.650,41.480,40.2144,34354028.0,2016-03-17,40.1500,40.960,40.0700,40.6100,39.3709,22160775.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1971,ORCL,2016-06-22,NaN,6.252000e+10,504000000.0,NaN,NaN,1.109030e+11,4.866300e+10,2.26,1.095500e+10,9.938000e+09,NaN,2.444300e+10,NaN,NaN,7.120000e+08,NaN,2.388000e+09,744000000.0,8.191000e+09,1.043100e+10,NaN,NaN,2.751000e+09,3.750000e+09,NaN,40.150,40.340,39.870,40.010,38.9332,12643366.0,2016-06-21,39.9300,40.120,39.7475,39.9900,38.9137,20111116.0,2016-06-23,40.400,40.8700,40.260,40.83,39.7311,15428483.0
1972,ORCL,2016-09-19,NaN,6.431300e+10,504000000.0,NaN,NaN,1.121800e+11,4.728900e+10,0.40,1.747000e+09,9.453000e+09,NaN,5.794000e+09,NaN,NaN,2.190000e+08,NaN,8.451000e+09,744000000.0,8.191000e+09,1.043100e+10,NaN,NaN,7.110000e+08,3.750000e+09,NaN,39.130,39.550,39.045,39.230,38.3143,19801878.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2016-09-20,39.550,39.6000,39.055,39.07,38.1580,12119101.0
1973,ORCL,2016-12-19,NaN,6.431300e+10,504000000.0,NaN,NaN,1.121800e+11,4.728900e+10,0.92,3.945000e+09,9.453000e+09,NaN,1.183200e+10,NaN,NaN,4.290000e+08,NaN,1.744700e+10,744000000.0,8.191000e+09,1.043100e+10,NaN,NaN,1.401000e+09,3.750000e+09,NaN,39.030,39.190,38.590,38.900,38.1392,15134543.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-20,38.960,39.1100,38.800,39.00,38.2373,14006387.0
1974,ORCL,2017-03-17,NaN,6.431300e+10,504000000.0,NaN,NaN,1.121800e+11,4.728900e+10,1.43,6.087000e+09,9.453000e+09,NaN,1.781700e+10,NaN,NaN,6.430000e+08,NaN,2.646100e+10,744000000.0,8.191000e+09,1.586900e+10,NaN,NaN,2.058000e+09,3.750000e+09,NaN,45.250,45.980,45.110,45.660,44.9412,31688720.0,2017-03-16,46.3900,46.990,45.6500,45.7300,45.0101,67535437.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1975,ORCL,2017-06-27,NaN,6.431300e+10,504000000.0,NaN,NaN,1.121800e+11,4.728900e+10,2.26,9.938000e+09,9.453000e+09,NaN,2.435500e+10,NaN,NaN,7.120000e+08,NaN,1.432800e+10,744000000.0,8.191000e+09,2.370900e+10,NaN,NaN,2.929000e+09,3.750000e+09,NaN,50.750,51.450,50.520,50.750,50.1668,17801028.0,2017-06-26,50.9900,51.700,50.7700,50.8600,50.2755,29327595.0,2017-06-28,51.070,51.0900,50.810,50.87,50.2854,15431884.0
1976,ORCL,2017-09-18,NaN,7.451500e+10,599000000.0,NaN,NaN,1.349910e+11,5.386000e+10,0.44,1.832000e+09,NaN,NaN,5.954000e+09,NaN,NaN,2.220000e+08,NaN,8.613000e+09,NaN,8.835000e+09,5.110000e+09,NaN,NaN,6.950000e+08,9.797000e+09,NaN,48.880,49.060,48.090,48.330,47.9546,29416689.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2017-09-19,48.490,48.5000,47.880,48.04,47.6668,22712871.0
1977,ORCL,2017-12-18,NaN,7.451500e+10,599000000.0,NaN,NaN,1.349910e+11,5.386000e+10,0.94,3.864000e+09,NaN,NaN,1.195200e+10,NaN,NaN,4.630000e+08,NaN,1.768300e+10,NaN,8.835000e+09,1.061800e+10,NaN,NaN,1.393000e+09,9.797000e+09,NaN,48.530,48.850,47.680,47.710,47.5259,24690916.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-19,47.985,48.3500,47.740,47.82,47.6355,28137680.0
1978,ORCL,2018-03-21,NaN,7.451500e+10,599000000.0,1.464800e+10,NaN,1.349910e+11,5.386000e+10,1.49,6.103000e+09,3.960000e+09,NaN,1.819900e+10,NaN,NaN,7.220000e+08,NaN,2.695700e+10,830000000.0,8.835000e+09,1.620200e+10,NaN,881000000.0,2.073000e+09,9.797000e+09,NaN,47.290,48.060,47.010,47.020,47.0200,34595470.0,2018-03-20,46.8000,47.750,46.4300,47.0500,47.0500,68331479.0,2018-03-22,46.720,47.0215,46.110,46.42,46.4200,9570792.0
1979,ORCL,2018-06-22,NaN,7.451500e+10,599000000.0,1.464800e+10,NaN,1.349910e+11,5.386000e+10,2.11,8.901000e+09,3.960000e+09,NaN,2.444300e+10,NaN,NaN,8.710000e+08,NaN,1.343500e+10,830000000.0,8.835000e+09,2.241000e+10,NaN,881000000.0,2.751000e+09,3.750000e+09,NaN,43.200,44.300,43.160,44.100,43.9278,30594322.0,2018-06-21,43.1800,43.840,42.9800,43.1000,42.9317,32635062.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1980,ORCL,2018-09-19,NaN,7.615900e+10,529000000.0,1.464800e+10,NaN,1.378510e+11,4.637200e+10,0.52,2.144000e+09,3.110000e+08,NaN,6.355000e+09,NaN,NaN,2.850000e+08,NaN,5.331000e+09,868000000.0,6.288000e+09,5.432000e+09,NaN,881000000.0,1.160000e+08,4.491000e+09,NaN,48.920,49.540,48.660,49.430,49.0389,20904826.0,2018-09-18,47.5100,49.540,47.3600,49.0300,48.6421,33451106.0,2018-09-20,49.660,51.0750,49.560,50.43,50.0310,26973480.0
1981,ORCL,2018-12-19,NaN,7.615900e+10,529000000.0,1.464800e+10,NaN,1.378510e+11,4.637200e+10,1.05,4.358000e+09,3.110000e+08,NaN,1.290400e+10,NaN,NaN,5.730000e+08,NaN,5.331000e+09,868000000.0,6.288000e+09,1.043100e+10,NaN,881000000.0,1.160000e+08,4.491000e+09,NaN,46.060,47.440,45.750,46.450,46.2683,34397250.0,2018-12-18,48.1000,48.340,45.4400,45.8500,45.6706,42855600.0,2018-12-20,46.050,46.9500,45.480,46.24,46.0591,35165179.0
1982,ORCL,2019-03-18,NaN,7.615900e+10,529000000.0,1.464800e+10,NaN,1.378510e+11,4.637200e+10,0.07,3.110000e+08,3.110000e+08,NaN,1.926600e+10,NaN,NaN,8.780000e+08,NaN,5.331000e+09,868000000.0,6.288000e+09,1.043100e+10,NaN,881000000.0,1.160000e+08,4.491000e+09,NaN,52.870,53.960,52.780,53.460,53.4600,21953604.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2019-03-19,53.800,54.3750,53.750,54.04,54.0400,19214018.0
1983,ORCL,2019-06-21,NaN,7.615900e+10,529000000.0,1.464800e+10,NaN,1.378510e+11,4.637200e+10,2.30,9.452000e+09,1.123500e+10,NaN,2.487900e+10,NaN,NaN,1.000000e+09,NaN,3.779200e+10,868000000.0,6.288000e+09,1.043100e+10,NaN,881000000.0,1.160000e+08,2.500000e+09,NaN,57.140,57.150,56.060,56.120,56.1200,45168973.0,2019-06-20,55.9800,57.470,55.5300,56.9900,56.9900,54173900.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN

Maybe I should just start with "simple" and impute the mean to the SEC filing columns. I will need a different decision for my day-plus/day-minus price information, though. I should probably just set those equal to the day-of prices when they're missing.

In [12]:
df_tech_rev['date_minus1'].fillna(value=df_tech_rev['date'], axis=0, inplace=True)
df_tech_rev.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 199 entries, 713 to 1983
Data columns (total 47 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ticker                            199 non-null    object
 1   date                              199 non-null    datetime64[ns]
 2   commonstocksharesissued           160 non-null    float64
 3   assetscurrent                     199 non-null    float64
 4   accountspayablecurrent            199 non-null    float64
 5   commonstockvalue                  19 non-null     float64
 6   liabilities                       122 non-null    float64
 7   liabilitiesandstockholdersequity  199 non-null    float64
 8   stockholdersequity                199 non-null    float64
 9   earningspersharebasic             199 non-null    float64
 10  netincomeloss                     199 non-null    float64
 11  profitloss                        124 non-null    float64
 12  costofgoodssold                   112 non-null    float64
 13  costsandexpenses                  119 non-null    float64
 14  cash                              20 non-null     float64
 15  preferredstockvalue               7 non-null      float64
 16  depreciation                      139 non-null    float64
 17  operatingexpenses                 78 non-null     float64
 18  revenues                          195 non-null    float64
 19  land                              37 non-null     float64
 20  deferredrevenue                   119 non-null    float64
 21  grossprofit                       119 non-null    float64
 22  sharesissued                      51 non-null     float64
 23  commercialpaper                   79 non-null     float64
 24  costofservices                    151 non-null    float64
 25  debtcurrent                       166 non-null    float64
 26  salariesandwages                  39 non-null     float64
 27  open                              198 non-null    float64
 28  high                              198 non-null    float64
 29  low                               198 non-null    float64
 30  close                             198 non-null    float64
 31  close_adjusted                    198 non-null    float64
 32  volume                            198 non-null    float64
 33  date_minus1                       199 non-null    datetime64[ns]
 34  open_minus1                       175 non-null    float64
 35  high_minus1                       175 non-null    float64
 36  low_minus1                        175 non-null    float64
 37  close_minus1                      175 non-null    float64
 38  close_adj_minus1                  175 non-null    float64
 39  volume_minus1                     175 non-null    float64
 40  date_plus1                        171 non-null    datetime64[ns]
 41  open_plus1                        171 non-null    float64
 42  high_plus1                        171 non-null    float64
 43  low_plus1                         171 non-null    float64
 44  close_plus1                       171 non-null    float64
 45  close_adj_plus1                   171 non-null    float64
 46  volume_plus1                      171 non-null    float64
dtypes: datetime64[ns](3), float64(43), object(1)
memory usage: 74.6+ KB

In [13]:
df_tech_rev['date_plus1'].fillna(value=df_tech_rev['date'], axis=0, inplace=True)
df_tech_rev['open_minus1'].fillna(value=df_tech_rev['open'], axis=0, inplace=True)
df_tech_rev['open_plus1'].fillna(value=df_tech_rev['open'], axis=0, inplace=True)
df_tech_rev['high_minus1'].fillna(value=df_tech_rev['high'], axis=0, inplace=True)
df_tech_rev['high_plus1'].fillna(value=df_tech_rev['high'], axis=0, inplace=True)
df_tech_rev['low_minus1'].fillna(value=df_tech_rev['low'], axis=0, inplace=True)
df_tech_rev['low_plus1'].fillna(value=df_tech_rev['low'], axis=0, inplace=True)
df_tech_rev['close_minus1'].fillna(value=df_tech_rev['close'], axis=0, inplace=True)
df_tech_rev['close_plus1'].fillna(value=df_tech_rev['close'], axis=0, inplace=True)
df_tech_rev['close_adj_minus1'].fillna(value=df_tech_rev['close_adjusted'], axis=0, inplace=True)
df_tech_rev['close_adj_plus1'].fillna(value=df_tech_rev['close_adjusted'], axis=0, inplace=True)
df_tech_rev['volume_minus1'].fillna(value=df_tech_rev['volume'], axis=0, inplace=True)
df_tech_rev['volume_plus1'].fillna(value=df_tech_rev['volume'], axis=0, inplace=True)
df_tech_rev.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 199 entries, 713 to 1983
Data columns (total 47 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ticker                            199 non-null    object
 1   date                              199 non-null    datetime64[ns]
 2   commonstocksharesissued           160 non-null    float64
 3   assetscurrent                     199 non-null    float64
 4   accountspayablecurrent            199 non-null    float64
 5   commonstockvalue                  19 non-null     float64
 6   liabilities                       122 non-null    float64
 7   liabilitiesandstockholdersequity  199 non-null    float64
 8   stockholdersequity                199 non-null    float64
 9   earningspersharebasic             199 non-null    float64
 10  netincomeloss                     199 non-null    float64
 11  profitloss                        124 non-null    float64
 12  costofgoodssold                   112 non-null    float64
 13  costsandexpenses                  119 non-null    float64
 14  cash                              20 non-null     float64
 15  preferredstockvalue               7 non-null      float64
 16  depreciation                      139 non-null    float64
 17  operatingexpenses                 78 non-null     float64
 18  revenues                          195 non-null    float64
 19  land                              37 non-null     float64
 20  deferredrevenue                   119 non-null    float64
 21  grossprofit                       119 non-null    float64
 22  sharesissued                      51 non-null     float64
 23  commercialpaper                   79 non-null     float64
 24  costofservices                    151 non-null    float64
 25  debtcurrent                       166 non-null    float64
 26  salariesandwages                  39 non-null     float64
 27  open                              198 non-null    float64
 28  high                              198 non-null    float64
 29  low                               198 non-null    float64
 30  close                             198 non-null    float64
 31  close_adjusted                    198 non-null    float64
 32  volume                            198 non-null    float64
 33  date_minus1                       199 non-null    datetime64[ns]
 34  open_minus1                       198 non-null    float64
 35  high_minus1                       198 non-null    float64
 36  low_minus1                        198 non-null    float64
 37  close_minus1                      198 non-null    float64
 38  close_adj_minus1                  198 non-null    float64
 39  volume_minus1                     198 non-null    float64
 40  date_plus1                        199 non-null    datetime64[ns]
 41  open_plus1                        199 non-null    float64
 42  high_plus1                        199 non-null    float64
 43  low_plus1                         199 non-null    float64
 44  close_plus1                       199 non-null    float64
 45  close_adj_plus1                   199 non-null    float64
 46  volume_plus1                      199 non-null    float64
dtypes: datetime64[ns](3), float64(43), object(1)
memory usage: 74.6+ KB

In [15]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df_tech_rev[df_tech_rev['open'].isnull()])

,ticker,date,commonstocksharesissued,assetscurrent,accountspayablecurrent,commonstockvalue,liabilities,liabilitiesandstockholdersequity,stockholdersequity,earningspersharebasic,netincomeloss,profitloss,costofgoodssold,costsandexpenses,cash,preferredstockvalue,depreciation,operatingexpenses,revenues,land,deferredrevenue,grossprofit,sharesissued,commercialpaper,costofservices,debtcurrent,salariesandwages,open,high,low,close,close_adjusted,volume,date_minus1,open_minus1,high_minus1,low_minus1,close_minus1,close_adj_minus1,volume_minus1,date_plus1,open_plus1,high_plus1,low_plus1,close_plus1,close_adj_plus1,volume_plus1
1375,IBM,2012-10-30,2.182470e+09,4.814100e+10,7.085000e+09,NaN,9.411200e+10,1.157780e+11,2.154100e+10,9.38,15000000.0,1.077100e+10,1.000300e+10,NaN,NaN,NaN,2.572000e+09,NaN,563000000.0,NaN,670000000.0,3.513100e+10,NaN,2.458000e+09,2.928500e+10,9.334000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-10-30,NaN,NaN,NaN,NaN,NaN,NaN,2012-10-31,194.8,196.41,193.63,194.53,166.5844,6052300.0

In [19]:
#sigh, fixing the ONE DARN ROW...
df_tech_rev.loc[1375,'date_minus1'] = df_tech_rev.loc[1375,'date_plus1'] #because date_minus1 had already been fillna'd
df_tech_rev['open_minus1'].fillna(value=df_tech_rev['open_plus1'], axis=0, inplace=True)
df_tech_rev['open'].fillna(value=df_tech_rev['open_plus1'], axis=0, inplace=True)
df_tech_rev['high_minus1'].fillna(value=df_tech_rev['high_plus1'], axis=0, inplace=True)
df_tech_rev['high'].fillna(value=df_tech_rev['high_plus1'], axis=0, inplace=True)
df_tech_rev['low_minus1'].fillna(value=df_tech_rev['low_plus1'], axis=0, inplace=True)
df_tech_rev['low'].fillna(value=df_tech_rev['low_plus1'], axis=0, inplace=True)
df_tech_rev['close_minus1'].fillna(value=df_tech_rev['close_plus1'], axis=0, inplace=True)
df_tech_rev['close'].fillna(value=df_tech_rev['close_plus1'], axis=0, inplace=True)
df_tech_rev['close_adj_minus1'].fillna(value=df_tech_rev['close_adj_plus1'], axis=0, inplace=True)
df_tech_rev['close_adjusted'].fillna(value=df_tech_rev['close_adj_plus1'], axis=0, inplace=True)
df_tech_rev['volume_minus1'].fillna(value=df_tech_rev['volume_plus1'], axis=0, inplace=True)
df_tech_rev['volume'].fillna(value=df_tech_rev['volume_plus1'], axis=0, inplace=True)
df_tech_rev.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 199 entries, 713 to 1983
Data columns (total 47 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ticker                            199 non-null    object
 1   date                              199 non-null    datetime64[ns]
 2   commonstocksharesissued           160 non-null    float64
 3   assetscurrent                     199 non-null    float64
 4   accountspayablecurrent            199 non-null    float64
 5   commonstockvalue                  19 non-null     float64
 6   liabilities                       122 non-null    float64
 7   liabilitiesandstockholdersequity  199 non-null    float64
 8   stockholdersequity                199 non-null    float64
 9   earningspersharebasic             199 non-null    float64
 10  netincomeloss                     199 non-null    float64
 11  profitloss                        124 non-null    float64
 12  costofgoodssold                   112 non-null    float64
 13  costsandexpenses                  119 non-null    float64
 14  cash                              20 non-null     float64
 15  preferredstockvalue               7 non-null      float64
 16  depreciation                      139 non-null    float64
 17  operatingexpenses                 78 non-null     float64
 18  revenues                          195 non-null    float64
 19  land                              37 non-null     float64
 20  deferredrevenue                   119 non-null    float64
 21  grossprofit                       119 non-null    float64
 22  sharesissued                      51 non-null     float64
 23  commercialpaper                   79 non-null     float64
 24  costofservices                    151 non-null    float64
 25  debtcurrent                       166 non-null    float64
 26  salariesandwages                  39 non-null     float64
 27  open                              199 non-null    float64
 28  high                              199 non-null    float64
 29  low                               199 non-null    float64
 30  close                             199 non-null    float64
 31  close_adjusted                    199 non-null    float64
 32  volume                            199 non-null    float64
 33  date_minus1                       199 non-null    datetime64[ns]
 34  open_minus1                       199 non-null    float64
 35  high_minus1                       199 non-null    float64
 36  low_minus1                        199 non-null    float64
 37  close_minus1                      199 non-null    float64
 38  close_adj_minus1                  199 non-null    float64
 39  volume_minus1                     199 non-null    float64
 40  date_plus1                        199 non-null    datetime64[ns]
 41  open_plus1                        199 non-null    float64
 42  high_plus1                        199 non-null    float64
 43  low_plus1                         199 non-null    float64
 44  close_plus1                       199 non-null    float64
 45  close_adj_plus1                   199 non-null    float64
 46  volume_plus1                      199 non-null    float64
dtypes: datetime64[ns](3), float64(43), object(1)
memory usage: 84.6+ KB

Whee! Now to try the magic of Pandas "interpolate"!

In [25]:
# credit: https://stackoverflow.com/questions/37057187/pandas-interpolate-within-a-groupby
df_tech_rev_interp = df_tech_rev.groupby('ticker').transform(pd.DataFrame.interpolate)
df_tech_rev_interp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 199 entries, 713 to 1983
Data columns (total 46 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   date                              199 non-null    datetime64[ns]
 1   commonstocksharesissued           160 non-null    float64
 2   assetscurrent                     199 non-null    float64
 3   accountspayablecurrent            199 non-null    float64
 4   commonstockvalue                  53 non-null     float64
 5   liabilities                       122 non-null    float64
 6   liabilitiesandstockholdersequity  199 non-null    float64
 7   stockholdersequity                199 non-null    float64
 8   earningspersharebasic             199 non-null    float64
 9   netincomeloss                     199 non-null    float64
 10  profitloss                        171 non-null    float64
 11  costofgoodssold                   118 non-null    float64
 12  costsandexpenses                  119 non-null    float64
 13  cash                              28 non-null     float64
 14  preferredstockvalue               28 non-null     float64
 15  depreciation                      145 non-null    float64
 16  operatingexpenses                 78 non-null     float64
 17  revenues                          199 non-null    float64
 18  land                              39 non-null     float64
 19  deferredrevenue                   119 non-null    float64
 20  grossprofit                       119 non-null    float64
 21  sharesissued                      54 non-null     float64
 22  commercialpaper                   133 non-null    float64
 23  costofservices                    157 non-null    float64
 24  debtcurrent                       171 non-null    float64
 25  salariesandwages                  40 non-null     float64
 26  open                              199 non-null    float64
 27  high                              199 non-null    float64
 28  low                               199 non-null    float64
 29  close                             199 non-null    float64
 30  close_adjusted                    199 non-null    float64
 31  volume                            199 non-null    float64
 32  date_minus1                       199 non-null    datetime64[ns]
 33  open_minus1                       199 non-null    float64
 34  high_minus1                       199 non-null    float64
 35  low_minus1                        199 non-null    float64
 36  close_minus1                      199 non-null    float64
 37  close_adj_minus1                  199 non-null    float64
 38  volume_minus1                     199 non-null    float64
 39  date_plus1                        199 non-null    datetime64[ns]
 40  open_plus1                        199 non-null    float64
 41  high_plus1                        199 non-null    float64
 42  low_plus1                         199 non-null    float64
 43  close_plus1                       199 non-null    float64
 44  close_adj_plus1                   199 non-null    float64
 45  volume_plus1                      199 non-null    float64
dtypes: datetime64[ns](3), float64(43)
memory usage: 83.1 KB

Well... this looks like it probably did what I hoped for, except it's made the ticker info disappear.

In [26]:
df_tech_rev_interp = df_tech_rev.groupby('ticker').apply(pd.DataFrame.interpolate)
df_tech_rev_interp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 199 entries, 713 to 1983
Data columns (total 47 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ticker                            199 non-null    object
 1   date                              199 non-null    datetime64[ns]
 2   commonstocksharesissued           160 non-null    float64
 3   assetscurrent                     199 non-null    float64
 4   accountspayablecurrent            199 non-null    float64
 5   commonstockvalue                  53 non-null     float64
 6   liabilities                       122 non-null    float64
 7   liabilitiesandstockholdersequity  199 non-null    float64
 8   stockholdersequity                199 non-null    float64
 9   earningspersharebasic             199 non-null    float64
 10  netincomeloss                     199 non-null    float64
 11  profitloss                        171 non-null    float64
 12  costofgoodssold                   118 non-null    float64
 13  costsandexpenses                  119 non-null    float64
 14  cash                              28 non-null     float64
 15  preferredstockvalue               28 non-null     float64
 16  depreciation                      145 non-null    float64
 17  operatingexpenses                 78 non-null     float64
 18  revenues                          199 non-null    float64
 19  land                              39 non-null     float64
 20  deferredrevenue                   119 non-null    float64
 21  grossprofit                       119 non-null    float64
 22  sharesissued                      54 non-null     float64
 23  commercialpaper                   133 non-null    float64
 24  costofservices                    157 non-null    float64
 25  debtcurrent                       171 non-null    float64
 26  salariesandwages                  40 non-null     float64
 27  open                              199 non-null    float64
 28  high                              199 non-null    float64
 29  low                               199 non-null    float64
 30  close                             199 non-null    float64
 31  close_adjusted                    199 non-null    float64
 32  volume                            199 non-null    float64
 33  date_minus1                       199 non-null    datetime64[ns]
 34  open_minus1                       199 non-null    float64
 35  high_minus1                       199 non-null    float64
 36  low_minus1                        199 non-null    float64
 37  close_minus1                      199 non-null    float64
 38  close_adj_minus1                  199 non-null    float64
 39  volume_minus1                     199 non-null    float64
 40  date_plus1                        199 non-null    datetime64[ns]
 41  open_plus1                        199 non-null    float64
 42  high_plus1                        199 non-null    float64
 43  low_plus1                         199 non-null    float64
 44  close_plus1                       199 non-null    float64
 45  close_adj_plus1                   199 non-null    float64
 46  volume_plus1                      199 non-null    float64
dtypes: datetime64[ns](3), float64(43), object(1)
memory usage: 74.6+ KB

That's odd. Wonder what's different between "apply" interpolate and "transform" interpolate. Let's see what it did.

In [27]:
with  pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df_tech_rev_interp[df_tech_rev_interp['ticker'] == 'GOOGL'])

,ticker,date,commonstocksharesissued,assetscurrent,accountspayablecurrent,commonstockvalue,liabilities,liabilitiesandstockholdersequity,stockholdersequity,earningspersharebasic,netincomeloss,profitloss,costofgoodssold,costsandexpenses,cash,preferredstockvalue,depreciation,operatingexpenses,revenues,land,deferredrevenue,grossprofit,sharesissued,commercialpaper,costofservices,debtcurrent,salariesandwages,open,high,low,close,close_adjusted,volume,date_minus1,open_minus1,high_minus1,low_minus1,close_minus1,close_adj_minus1,volume_minus1,date_plus1,open_plus1,high_plus1,low_plus1,close_plus1,close_adj_plus1,volume_plus1
1160,GOOGL,2015-10-29,50990000.0,8.810300e+10,1.549000e+09,51000.0,2.617800e+10,1.442810e+11,1.162410e+11,15.95,8.310000e+08,-208000000.0,NaN,3.968000e+10,NaN,NaN,NaN,NaN,2.399800e+10,NaN,NaN,NaN,687348000.0,2.000000e+09,NaN,3.237000e+09,NaN,736.63,746.790,735.16,744.85,744.85,1825957.0,2015-10-28,733.00,737.37,727.27,736.92,736.92,1980154.0,2015-10-30,745.56,746.31,736.5300,737.39,737.39,1999161.0
1161,GOOGL,2016-02-11,50295000.0,9.011400e+10,1.931000e+09,50000.0,2.617800e+10,1.474610e+11,8.922300e+10,23.11,1.634800e+10,-208000000.0,NaN,5.562900e+10,NaN,NaN,NaN,NaN,3.311200e+10,NaN,NaN,NaN,687348000.0,2.000000e+09,NaN,3.225000e+09,NaN,696.34,712.315,691.19,706.36,706.36,3250206.0,2016-02-10,711.79,723.22,705.39,706.85,706.85,3015733.0,2016-02-12,712.21,716.00,701.5800,706.89,706.89,2326889.0
1162,GOOGL,2016-05-03,49536000.0,9.095500e+10,1.667000e+09,50125.0,2.617800e+10,1.497470e+11,-1.891000e+09,6.12,4.207000e+09,-169000000.0,NaN,1.491500e+10,NaN,NaN,NaN,NaN,8.955000e+09,NaN,NaN,NaN,691293000.0,1.912500e+09,NaN,3.221000e+09,NaN,712.50,713.370,707.33,708.44,708.44,1931040.0,2016-05-02,711.92,715.41,706.36,714.41,714.41,1673820.0,2016-05-04,706.77,715.05,704.0500,711.37,711.37,1708609.0
1163,GOOGL,2016-08-04,48921000.0,9.423800e+10,1.716000e+09,50250.0,2.641300e+10,1.542920e+11,-2.010000e+09,13.23,6.560000e+08,-183000000.0,NaN,3.044700e+10,NaN,NaN,NaN,NaN,1.850600e+10,NaN,NaN,NaN,691293000.0,1.825000e+09,NaN,2.219000e+09,NaN,798.24,800.200,793.92,797.25,797.25,1076031.0,2016-08-03,796.47,799.54,793.02,798.92,798.92,1461025.0,2016-08-05,800.11,807.22,797.8100,806.93,806.93,1807271.0
1164,GOOGL,2016-11-03,48105000.0,9.854600e+10,2.175000e+09,50375.0,2.584500e+10,1.599480e+11,-1.881000e+09,20.59,1.013000e+09,-137000000.0,NaN,4.713100e+10,NaN,NaN,NaN,NaN,2.841800e+10,NaN,NaN,NaN,691293000.0,1.737500e+09,NaN,2.070667e+09,NaN,784.50,790.000,778.63,782.19,782.19,2175216.0,2016-11-02,806.76,806.76,785.00,788.42,788.42,2350736.0,2016-11-04,771.30,788.48,771.0043,781.10,781.10,1970603.0
1165,GOOGL,2017-02-03,47437000.0,1.054080e+11,2.041000e+09,50500.0,2.846100e+10,1.674970e+11,1.051310e+11,28.32,1.947800e+10,-151200000.0,NaN,6.655600e+10,NaN,NaN,NaN,NaN,3.970400e+10,NaN,NaN,NaN,691293000.0,1.650000e+09,NaN,1.922333e+09,NaN,823.13,826.130,819.35,820.13,820.13,1528095.0,2017-02-02,815.00,824.56,812.05,818.26,818.26,1689179.0,2017-02-03,823.13,826.13,819.3500,820.13,820.13,1528095.0
1166,GOOGL,2017-05-02,47164000.0,1.087940e+11,2.306000e+09,50625.0,2.780700e+10,1.727560e+11,-2.195000e+09,7.85,-2.500000e+07,-165400000.0,NaN,1.818200e+10,NaN,NaN,NaN,NaN,8.091000e+09,NaN,NaN,NaN,692165500.0,1.562500e+09,NaN,1.774000e+09,NaN,933.27,942.990,931.00,937.09,937.09,1745453.0,2017-05-01,924.15,935.82,920.80,932.82,932.82,2294856.0,2017-05-03,936.05,950.20,935.2100,948.45,948.45,1792847.0
1167,GOOGL,2017-07-25,47101000.0,1.123860e+11,2.488000e+09,50750.0,3.033500e+10,1.786210e+11,-1.630000e+09,12.94,-5.100000e+07,-179600000.0,NaN,4.006000e+10,NaN,NaN,NaN,NaN,1.663600e+10,NaN,NaN,NaN,693038000.0,1.475000e+09,NaN,1.625667e+09,NaN,970.70,976.730,963.80,969.03,969.03,5793414.0,2017-07-24,994.10,1006.19,990.27,998.31,998.31,3053176.0,2017-07-26,972.78,973.95,960.2300,965.31,965.31,2166225.0
1168,GOOGL,2017-10-27,47054000.0,1.193450e+11,2.674000e+09,50875.0,3.243600e+10,1.895360e+11,-1.189000e+09,22.65,-9.800000e+07,-193800000.0,NaN,6.005000e+10,NaN,NaN,NaN,NaN,2.573300e+10,NaN,NaN,NaN,693910500.0,1.387500e+09,NaN,1.477333e+09,NaN,1030.99,1063.620,1026.85,1033.67,1033.67,5139945.0,2017-10-26,998.47,1006.51,990.47,991.42,991.42,1827682.0,2017-10-27,1030.99,1063.62,1026.8500,1033.67,1033.67,5139945.0
1169,GOOGL,2018-02-06,46972000.0,1.243080e+11,3.137000e+09,51000.0,4.479300e+10,1.972950e+11,1.132470e+11,18.27,1.266200e+10,-208000000.0,NaN,8.470900e+10,NaN,NaN,NaN,NaN,3.604600e+10,NaN,NaN,NaN,694783000.0,1.300000e+09,NaN,1.329000e+09,NaN,1033.98,1087.380,1030.01,1084.43,1084.43,3732527.0,2018-02-05,1100.61,1114.99,1056.74,1062.39,1062.39,3742469.0,2018-02-07,1084.97,1086.53,1054.6200,1055.41,1055.41,2544683.0
1170,GOOGL,2018-04-24,46940000.0,1.237610e+11,3.526000e+09,51000.0,4.611000e+10,2.069350e+11,-4.460000e+08,13.53,-3.900000e+07,-208000000.0,NaN,2.414500e+10,NaN,NaN,NaN,NaN,1.500000e+08,NaN,NaN,NaN,695556000.0,1.300000e+09,NaN,1.329000e+09,NaN,1059.20,1064.490,1012.86,1022.64,1022.64,6411038.0,2018-04-23,1082.98,1088.00,1066.68,1073.81,1073.81,3479496.0,2018-04-25,1029.75,1036.07,1017.0100,1022.99,1022.99,2893047.0
1171,GOOGL,2018-07-24,46891000.0,1.241570e+11,3.369000e+09,51000.0,4.961000e+10,2.116100e+11,-1.588000e+09,18.13,-3.300000e+07,-208000000.0,NaN,5.399500e+10,NaN,NaN,NaN,NaN,2.950000e+08,NaN,NaN,NaN,695556000.0,2.000000e+09,NaN,3.237000e+09,NaN,1271.00,1275.000,1244.14,1258.15,1258.15,5380032.0,2018-07-23,1195.66,1215.10,1192.01,1211.00,1211.00,3272304.0,2018-07-25,1252.62,1278.24,1249.0500,1275.94,1275.94,2575437.0
1172,GOOGL,2018-10-26,46880000.0,1.297020e+11,3.789000e+09,51000.0,5.169800e+10,2.215380e+11,-1.569000e+09,31.34,-6.200000e+07,-208000000.0,NaN,7.942500e+10,NaN,NaN,NaN,NaN,4.410000e+08,NaN,NaN,NaN,695556000.0,2.000000e+09,NaN,3.237000e+09,NaN,1048.33,1117.000,1042.23,1083.75,1083.75,5321883.0,2018-10-25,1080.30,1117.82,1075.55,1103.59,1103.59,3647814.0,2018-10-26,1048.33,1117.00,1042.2300,1083.75,1083.75,5321883.0
1173,GOOGL,2019-02-05,46636000.0,1.356760e+11,4.378000e+09,51000.0,5.516400e+10,2.327920e+11,1.348850e+11,44.22,3.073600e+10,-208000000.0,NaN,1.104980e+11,NaN,NaN,NaN,NaN,2.399800e+10,NaN,NaN,NaN,695556000.0,2.000000e+09,NaN,3.237000e+09,NaN,1129.63,1152.770,1123.60,1151.87,1151.87,4114790.0,2019-02-04,1119.01,1142.34,1117.51,1141.42,1141.42,3920591.0,2019-02-06,1149.27,1154.00,1118.3600,1122.89,1122.89,2412820.0

In [28]:
with  pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df_tech_rev_interp[df_tech_rev_interp['ticker'] == 'FB'])

,ticker,date,commonstocksharesissued,assetscurrent,accountspayablecurrent,commonstockvalue,liabilities,liabilitiesandstockholdersequity,stockholdersequity,earningspersharebasic,netincomeloss,profitloss,costofgoodssold,costsandexpenses,cash,preferredstockvalue,depreciation,operatingexpenses,revenues,land,deferredrevenue,grossprofit,sharesissued,commercialpaper,costofservices,debtcurrent,salariesandwages,open,high,low,close,close_adjusted,volume,date_minus1,open_minus1,high_minus1,low_minus1,close_minus1,close_adj_minus1,volume_minus1,date_plus1,open_plus1,high_plus1,low_plus1,close_plus1,close_adj_plus1,volume_plus1
980,FB,2012-07-31,1.170000e+08,4.604000e+09,63000000.0,NaN,1.432000e+09,6.331000e+09,4.899000e+09,-0.08,-3.100000e+07,NaN,NaN,1.927000e+09,1.513000e+09,615000000.0,5.660000e+08,NaN,5.960000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.3700,23.37,21.61,21.7100,21.7100,56179400.0,2012-07-30,23.9950,24.040,23.0300,23.150,23.150,29285900.0,2012-08-01,21.50,21.58,20.840,20.880,20.880,44604400.0
981,FB,2012-10-24,1.800000e+08,1.228500e+10,63000000.0,NaN,1.432000e+09,6.331000e+09,1.417400e+10,-0.02,-3.000000e+06,NaN,NaN,1.371000e+09,1.513000e+09,615000000.0,5.660000e+08,NaN,5.430000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.1300,24.25,22.85,23.2299,23.2299,228949900.0,2012-10-23,19.2500,19.800,19.1000,19.500,19.500,78381200.0,2012-10-25,23.29,23.31,22.470,22.560,22.560,76142000.0
982,FB,2013-02-01,1.170000e+08,1.126700e+10,63000000.0,NaN,1.432000e+09,6.331000e+09,2.162000e+09,0.02,3.500000e+07,NaN,NaN,9.420000e+08,1.513000e+09,615000000.0,5.660000e+08,NaN,1.644000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.0100,31.02,29.63,29.7300,29.7300,85856700.0,2013-01-31,29.1500,31.470,28.7400,30.981,30.981,190744900.0,2013-02-01,31.01,31.02,29.630,29.730,29.730,85856700.0
983,FB,2013-05-02,1.671000e+09,1.104200e+10,65000000.0,NaN,3.348000e+09,1.510300e+10,1.182400e+10,0.10,1.560000e+08,NaN,NaN,1.085000e+09,1.166000e+09,615000000.0,5.660000e+08,NaN,5.220000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0099,29.02,27.98,28.9700,28.9700,104257000.0,2013-05-01,27.8500,27.915,27.3100,27.430,27.430,64567600.0,2013-05-03,29.04,29.07,28.150,28.311,28.311,58506400.0
984,FB,2013-07-25,7.010000e+08,1.142100e+10,65000000.0,NaN,3.348000e+09,1.510300e+10,1.234900e+10,-0.08,-1.260000e+08,NaN,NaN,1.251000e+09,1.020000e+09,615000000.0,5.660000e+08,NaN,1.124000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.5450,34.88,32.75,34.3590,34.3590,365457900.0,2013-07-24,26.3200,26.530,26.0500,26.510,26.510,82635600.0,2013-07-26,33.77,34.73,33.560,34.010,34.010,136028900.0
985,FB,2013-11-01,7.010000e+08,1.054900e+10,65000000.0,NaN,3.348000e+09,1.510300e+10,1.304800e+10,0.17,2.600000e+08,NaN,NaN,1.280000e+09,8.980000e+08,615000000.0,5.660000e+08,NaN,1.789000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.8500,52.09,49.72,49.7500,49.7500,95033000.0,2013-10-31,47.1550,52.000,46.5000,50.205,50.205,248809000.0,2013-11-01,50.85,52.09,49.720,49.750,49.750,95033000.0
986,FB,2014-01-31,7.010000e+08,1.307000e+10,87000000.0,NaN,3.348000e+09,1.510300e+10,-6.000000e+06,0.52,3.500000e+07,NaN,NaN,5.068000e+09,1.044000e+09,615000000.0,5.660000e+08,NaN,1.644000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.4700,63.37,60.17,62.5700,62.5700,87794600.0,2014-01-30,62.1200,62.500,60.4600,61.080,61.080,150178900.0,2014-01-31,60.47,63.37,60.170,62.570,62.570,87794600.0
987,FB,2014-04-25,1.970000e+09,1.406000e+10,85000000.0,NaN,2.425000e+09,1.902800e+10,1.673700e+10,0.09,1.440000e+08,NaN,NaN,1.427000e+09,1.044000e+09,615000000.0,9.230000e+08,NaN,7.770000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.9700,60.01,57.57,57.7100,57.7100,92502000.0,2014-04-24,63.6000,63.650,59.7700,60.870,60.870,138769000.0,2014-04-25,59.97,60.01,57.570,57.710,57.710,92502000.0
988,FB,2014-07-24,2.013000e+09,1.555700e+10,146000000.0,NaN,2.425000e+09,2.076900e+10,1.834600e+10,0.31,3.170000e+08,NaN,NaN,2.948000e+09,1.044000e+09,615000000.0,9.230000e+08,NaN,3.023000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.9600,76.74,74.51,74.9800,74.9800,124006900.0,2014-07-23,69.7400,71.330,69.6100,71.290,71.290,77435900.0,2014-07-25,74.99,75.67,74.662,75.190,75.190,45823100.0
989,FB,2014-10-30,5.640000e+08,1.611500e+10,87000000.0,NaN,2.425000e+09,2.418800e+10,1.547000e+10,0.40,6.320000e+08,NaN,NaN,4.754000e+09,1.344000e+09,615000000.0,9.230000e+08,NaN,4.758000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.0500,75.35,72.90,74.1100,74.1100,83269554.0,2014-10-29,75.4500,76.880,74.7800,75.860,75.860,106119520.0,2014-10-31,74.93,75.70,74.450,74.990,74.990,44544325.0
990,FB,2015-01-29,5.627922e+08,1.367000e+10,176000000.0,NaN,4.088000e+09,4.018400e+10,3.609600e+10,1.12,2.940000e+09,NaN,NaN,7.472000e+09,2.162000e+09,615000000.0,9.230000e+08,NaN,6.817000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.8500,78.02,74.21,78.0000,78.0000,61293468.0,2015-01-28,76.9000,77.638,76.0000,76.240,76.240,53306422.0,2015-01-30,78.00,78.16,75.750,75.910,75.910,42649491.0
991,FB,2015-04-23,5.590000e+08,1.500400e+10,129000000.0,NaN,4.506000e+09,4.200700e+10,3.750100e+10,0.18,1.020000e+08,NaN,NaN,2.610000e+09,2.644000e+09,615000000.0,1.220000e+09,NaN,1.891000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.1000,85.59,82.41,82.4100,82.4100,73728080.0,2015-04-22,84.3200,84.740,83.6500,84.630,84.630,45547963.0,2015-04-24,82.77,82.94,81.480,81.530,81.530,29660356.0
992,FB,2015-07-31,5.580000e+08,1.695100e+10,139000000.0,NaN,4.678000e+09,4.413000e+10,3.945200e+10,0.44,2.440000e+08,NaN,NaN,5.380000e+09,2.300000e+09,615000000.0,1.220000e+09,NaN,4.053000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.9500,96.33,93.95,94.0100,94.0100,46509045.0,2015-07-30,94.9100,95.810,91.8000,95.210,95.210,86211323.0,2015-07-31,94.95,96.33,93.950,94.010,94.010,46509045.0
993,FB,2015-11-05,5.580000e+08,1.913900e+10,149000000.0,NaN,5.049000e+09,4.646900e+10,4.142000e+10,0.76,4.220000e+08,NaN,NaN,8.422000e+09,2.687000e+09,615000000.0,1.220000e+09,NaN,6.388000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.8000,110.65,107.95,108.7600,108.7600,63232861.0,2015-11-04,103.1900,104.140,102.4800,103.940,103.940,43469308.0,2015-11-06,108.04,108.74,105.910,107.095,107.095,35084342.0
994,FB,2016-01-28,5.520000e+08,2.165200e+10,196000000.0,NaN,5.189000e+09,4.940700e+10,4.421800e+10,1.31,3.688000e+09,NaN,NaN,1.170300e+10,2.556556e+09,615000000.0,1.220000e+09,NaN,9.415000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.2000,110.34,104.81,109.1100,109.1100,107475327.0,2016-01-27,97.7900,97.850,94.2300,94.450,94.450,58699359.0,2016-01-29,108.99,112.84,108.840,112.210,112.210,62739548.0
995,FB,2016-04-28,5.490000e+08,2.381200e+10,149000000.0,NaN,4.925000e+09,5.207500e+10,4.715000e+10,0.53,2.910000e+08,NaN,NaN,3.373000e+09,2.426111e+09,615000000.0,1.590000e+09,NaN,2.873000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.5750,120.79,116.23,116.7300,116.7300,87110080.0,2016-04-27,107.9400,108.940,106.3100,108.890,108.890,52213107.0,2016-04-29,116.82,117.84,115.840,117.580,117.580,37140594.0
996,FB,2016-07-28,5.480000e+08,2.701000e+10,130000000.0,NaN,5.356000e+09,5.573900e+10,5.038300e+10,1.25,6.840000e+08,NaN,NaN,7.064000e+09,2.295667e+09,615000000.0,1.590000e+09,NaN,6.457000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,127.5200,128.33,123.63,125.0000,125.0000,78955758.0,2016-07-27,122.4200,125.000,121.5100,123.340,123.340,52654239.0,2016-07-29,124.65,125.84,123.710,123.940,123.940,35058803.0
997,FB,2016-11-03,5.460000e+08,3.032800e+10,260000000.0,NaN,5.559000e+09,5.967400e+10,5.411500e+10,2.07,1.138000e+09,NaN,NaN,1.095300e+10,2.165222e+09,615000000.0,1.590000e+09,NaN,1.028400e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,122.0000,123.28,119.50,120.0000,120.0000,63766259.0,2016-11-02,130.2300,130.230,126.2800,127.170,127.170,50190225.0,2016-11-04,119.59,121.93,119.250,120.750,120.750,30545466.0
998,FB,2017-02-03,5.380000e+08,3.440100e+10,302000000.0,NaN,5.767000e+09,6.496100e+10,2.167000e+10,3.56,1.021700e+10,NaN,NaN,1.521100e+10,2.034778e+09,615000000.0,1.590000e+09,NaN,1.505900e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,131.2400,132.85,130.76,130.9800,130.9800,24804890.0,2017-02-02,133.2200,135.490,130.4000,130.840,130.840,54366447.0,2017-02-03,131.24,132.85,130.760,130.980,130.980,24804890.0
999,FB,2017-05-04,5.340000e+08,3.693000e+10,170000000.0,NaN,6.526000e+09,6.871400e+10,6.218800e+10,1.06,5.670000e+08,NaN,NaN,4.705000e+09,1.904333e+09,615000000.0,1.775000e+09,NaN,4.505000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150.1700,151.52,148.72,150.8500,150.8500,36060301.0,2017-05-03,153.6000,153.600,151.3400,151.800,151.800,21755088.0,2017-05-05,151.45,151.63,149.790,150.240,150.240,17051519.0
1000,FB,2017-07-27,5.320000e+08,4.080400e+10,323000000.0,NaN,7.362000e+09,7.384300e+10,6.648100e+10,2.40,1.286000e+09,NaN,NaN,9.624000e+09,1.773889e+09,615000000.0,1.960000e+09,NaN,9.779000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174.7000,175.49,167.50,170.4400,170.4400,68065163.0,2017-07-26,166.0100,166.010,164.1000,165.610,165.610,24081060.0,2017-07-28,169.07,173.43,169.050,172.450,172.450,24036502.0
1001,FB,2017-11-02,5.210000e+08,4.420300e+10,383000000.0,NaN,7.790000e+09,7.899800e+10,7.120800e+10,4.02,2.142000e+09,NaN,NaN,1.483000e+10,1.643444e+09,615000000.0,2.145000e+09,NaN,1.562400e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.6300,181.94,177.34,178.9200,178.9200,35119841.0,2017-11-01,182.3600,182.900,180.5700,182.660,182.660,28922959.0,2017-11-03,179.29,179.86,176.710,178.920,178.920,17572587.0
1002,FB,2018-02-01,5.090000e+08,4.856300e+10,380000000.0,NaN,1.017700e+10,8.452400e+10,3.399000e+10,5.49,1.593400e+10,NaN,NaN,2.045000e+10,1.513000e+09,615000000.0,2.330000e+09,NaN,2.291900e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188.2200,195.32,187.89,193.0900,193.0900,53608910.0,2018-01-31,188.3700,189.830,185.2200,186.890,186.890,27299152.0,2018-02-02,192.04,194.21,189.980,190.280,190.280,25514560.0
1003,FB,2018-04-26,4.980000e+08,5.041200e+10,593000000.0,NaN,1.132500e+10,8.894500e+10,7.762000e+10,1.72,8.650000e+08,NaN,NaN,6.517000e+09,1.513000e+09,615000000.0,3.680000e+09,NaN,1.196600e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173.2200,176.27,170.80,174.1600,174.1600,77556934.0,2018-04-25,160.1448,161.060,156.1900,159.690,159.690,41083581.0,2018-04-27,176.81,177.10,172.600,173.590,173.590,29773114.0
1004,FB,2018-07-26,4.780000e+08,4.983300e+10,419000000.0,NaN,1.090900e+10,9.029100e+10,7.938200e+10,3.48,1.725000e+09,NaN,NaN,1.388400e+10,1.513000e+09,615000000.0,3.680000e+09,NaN,2.519700e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174.8900,180.13,173.75,176.2600,176.2600,169803668.0,2018-07-25,215.7150,218.620,214.2700,217.500,217.500,64592585.0,2018-07-27,179.87,179.93,173.000,174.890,174.890,60073749.0
1005,FB,2018-10-31,4.710000e+08,4.914700e+10,590000000.0,NaN,1.211000e+10,9.245200e+10,3.876700e+10,5.26,1.523000e+10,NaN,NaN,2.183100e+10,1.513000e+09,615000000.0,3.680000e+09,NaN,3.892400e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,155.0000,156.40,148.96,151.7900,151.7900,60101251.0,2018-10-30,139.9350,146.640,139.7419,146.220,146.220,50528278.0,2018-11-01,151.52,152.75,149.350,151.750,151.750,25640786.0
1006,FB,2019-01-31,4.690000e+08,5.048000e+10,820000000.0,NaN,1.320700e+10,9.733400e+10,4.198100e+10,7.65,2.211200e+10,NaN,NaN,3.092500e+10,1.513000e+09,615000000.0,3.680000e+09,NaN,5.960000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165.6000,171.68,165.00,166.6900,166.6900,77233602.0,2019-01-30,146.2200,150.950,145.6953,150.420,150.420,44613240.0,2019-02-01,165.84,169.10,165.660,165.710,165.710,30806513.0
1007,FB,2019-04-25,4.520000e+08,5.330000e+10,604000000.0,NaN,2.296100e+10,1.094770e+11,4.376400e+10,0.85,2.429000e+09,NaN,NaN,1.176000e+10,1.513000e+09,615000000.0,5.660000e+08,NaN,5.960000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,196.9800,198.48,192.12,193.2600,193.2600,54062549.0,2019-04-24,184.4900,185.140,181.6500,182.580,182.580,37289871.0,2019-04-26,192.50,192.90,189.090,191.490,191.490,22075002.0

In [29]:
with  pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df_tech_rev_interp[df_tech_rev_interp['ticker'] == 'ORCL'])

,ticker,date,commonstocksharesissued,assetscurrent,accountspayablecurrent,commonstockvalue,liabilities,liabilitiesandstockholdersequity,stockholdersequity,earningspersharebasic,netincomeloss,profitloss,costofgoodssold,costsandexpenses,cash,preferredstockvalue,depreciation,operatingexpenses,revenues,land,deferredrevenue,grossprofit,sharesissued,commercialpaper,costofservices,debtcurrent,salariesandwages,open,high,low,close,close_adjusted,volume,date_minus1,open_minus1,high_minus1,low_minus1,close_minus1,close_adj_minus1,volume_minus1,date_plus1,open_plus1,high_plus1,low_plus1,close_plus1,close_adj_plus1,volume_plus1
1945,ORCL,2009-09-21,NaN,1.858100e+10,271000000.0,1.464800e+10,NaN,5.299800e+10,2.614300e+10,0.21,9.452000e+09,1.123500e+10,NaN,3.810000e+09,NaN,NaN,6.400000e+07,NaN,5.331000e+09,8.680000e+08,6.288000e+09,1.043100e+10,NaN,881000000.0,1.160000e+08,2.500000e+09,NaN,21.560,21.820,21.500,21.570,19.5155,25487400.0,2009-09-21,21.5600,21.820,21.5000,21.5700,19.5155,25487400.0,2009-09-22,21.590,21.7075,21.350,21.41,19.3708,34159300.0
1946,ORCL,2009-12-22,NaN,2.523500e+10,255000000.0,1.464800e+10,NaN,5.383300e+10,2.753100e+10,0.46,9.452000e+09,1.123500e+10,NaN,7.442000e+09,NaN,NaN,1.230000e+08,NaN,1.093800e+10,8.680000e+08,6.288000e+09,1.043100e+10,NaN,881000000.0,1.160000e+08,2.500000e+09,NaN,24.510,24.630,24.240,24.460,22.1836,23847200.0,2009-12-21,24.3900,24.570,24.2200,24.4300,22.1564,26935500.0,2009-12-23,24.460,24.7500,24.360,24.73,22.4285,19257800.0
1947,ORCL,2010-03-29,NaN,2.397900e+10,616000000.0,1.464800e+10,NaN,5.938600e+10,2.847600e+10,0.73,9.452000e+09,1.123500e+10,NaN,1.095500e+10,NaN,NaN,1.960000e+08,NaN,1.639100e+10,8.680000e+08,6.288000e+09,1.043100e+10,NaN,881000000.0,1.160000e+08,2.500000e+09,NaN,25.645,25.850,25.410,25.570,23.2361,28975300.0,2010-03-29,25.6450,25.850,25.4100,25.5700,23.2361,28975300.0,2010-03-30,25.480,25.5800,25.220,25.54,23.2088,29819400.0
1948,ORCL,2010-07-01,NaN,1.858100e+10,271000000.0,1.464800e+10,NaN,6.157800e+10,2.509000e+10,1.08,6.230000e+09,5.593000e+09,NaN,1.458600e+10,NaN,NaN,2.980000e+08,NaN,2.243000e+10,7.570000e+08,6.288000e+09,1.043100e+10,NaN,881000000.0,1.160000e+08,2.950000e+09,NaN,21.460,21.680,21.240,21.550,19.6204,38318200.0,2010-06-30,21.6400,21.960,21.3900,21.4600,19.5384,35301600.0,2010-07-02,21.710,22.0300,21.490,21.83,19.8753,31784000.0
1949,ORCL,2010-12-21,NaN,2.700400e+10,775000000.0,1.464800e+10,NaN,6.157800e+10,3.079800e+10,0.52,9.981000e+09,5.593000e+09,NaN,6.993000e+09,NaN,NaN,1.230000e+08,NaN,1.608400e+10,7.570000e+08,6.288000e+09,1.043100e+10,NaN,881000000.0,1.160000e+08,2.950000e+09,NaN,31.650,32.000,31.590,31.760,29.0318,20002800.0,2010-12-20,31.5400,31.940,31.1100,31.6750,28.9541,33568100.0,2010-12-22,31.680,31.8825,31.560,31.66,28.9404,14019200.0
1950,ORCL,2011-03-29,NaN,2.700400e+10,775000000.0,1.464800e+10,NaN,6.157800e+10,3.079800e+10,0.75,9.981000e+09,5.593000e+09,NaN,1.155300e+10,NaN,NaN,1.960000e+08,NaN,2.484700e+10,7.570000e+08,6.288000e+09,1.043100e+10,NaN,881000000.0,1.160000e+08,2.950000e+09,NaN,32.400,33.160,32.360,33.160,30.3601,29950300.0,2011-03-28,32.8300,32.890,32.4000,32.5550,29.8062,31399500.0,2011-03-30,33.270,33.4300,33.000,33.05,30.2594,25718200.0
1951,ORCL,2011-06-28,NaN,3.917400e+10,701000000.0,1.464800e+10,NaN,7.353500e+10,3.977600e+10,1.69,9.981000e+09,5.593000e+09,NaN,2.358900e+10,NaN,NaN,2.980000e+08,NaN,2.325200e+10,7.570000e+08,7.118000e+09,1.043100e+10,NaN,881000000.0,1.259000e+09,2.950000e+09,NaN,31.690,32.370,31.370,32.340,29.6619,32746800.0,2011-06-27,30.9800,31.830,30.8600,31.5800,28.9648,29585600.0,2011-06-29,32.400,32.6800,32.210,32.43,29.7445,27305700.0
1952,ORCL,2011-09-23,NaN,3.917400e+10,701000000.0,1.464800e+10,NaN,7.353500e+10,3.977600e+10,0.27,9.981000e+09,6.230000e+09,NaN,5.585000e+09,NaN,NaN,9.900000e+07,NaN,8.374000e+09,6.920000e+08,7.118000e+09,1.043100e+10,NaN,881000000.0,8.960000e+08,2.950000e+09,NaN,28.100,29.080,27.810,28.900,26.5548,43991700.0,2011-09-22,28.7400,29.030,27.8309,28.3400,26.0402,61371400.0,2011-09-23,28.100,29.0800,27.810,28.90,26.5548,43991700.0
1953,ORCL,2011-12-23,NaN,3.848200e+10,445000000.0,1.464800e+10,NaN,7.291000e+10,4.192000e+10,0.43,9.981000e+09,6.230000e+09,NaN,5.681000e+09,NaN,NaN,2.260000e+08,NaN,8.792000e+09,6.920000e+08,6.360000e+09,1.043100e+10,NaN,881000000.0,9.290000e+08,2.950000e+09,NaN,25.800,26.080,25.750,26.060,23.9933,32292800.0,2011-12-22,25.8601,25.870,25.3800,25.6900,23.6526,44203700.0,2011-12-23,25.800,26.0800,25.750,26.06,23.9933,32292800.0
1954,ORCL,2012-03-23,NaN,3.753800e+10,442000000.0,1.464800e+10,NaN,7.436100e+10,4.287300e+10,0.50,9.981000e+09,6.230000e+09,NaN,5.722000e+09,NaN,NaN,2.830000e+08,NaN,9.039000e+09,6.920000e+08,6.591000e+09,1.043100e+10,NaN,881000000.0,9.220000e+08,2.950000e+09,NaN,28.690,28.890,28.520,28.550,26.3441,36696300.0,2012-03-22,29.3300,29.330,28.5600,28.6300,26.4180,59763200.0,2012-03-23,28.690,28.8900,28.520,28.55,26.3441,36696300.0
1955,ORCL,2012-06-26,NaN,4.002300e+10,438000000.0,1.464800e+10,NaN,7.832700e+10,4.368800e+10,1.99,9.981000e+09,6.230000e+09,NaN,2.341500e+10,NaN,NaN,3.680000e+08,NaN,3.712100e+10,6.920000e+08,7.331000e+09,1.043100e+10,NaN,881000000.0,3.743000e+09,2.950000e+09,NaN,27.630,27.945,27.515,27.830,25.7329,20614200.0,2012-06-25,27.5400,27.750,27.2400,27.6200,25.5387,24918800.0,2012-06-27,27.760,28.4550,27.760,28.17,26.0473,19388200.0
1956,ORCL,2012-09-24,NaN,3.817200e+10,388000000.0,1.464800e+10,NaN,7.655800e+10,4.332900e+10,0.36,1.840000e+09,8.547000e+09,NaN,5.691000e+09,NaN,NaN,1.170000e+08,NaN,8.181000e+09,6.320000e+08,7.331000e+09,1.043100e+10,NaN,881000000.0,9.360000e+08,1.250000e+09,NaN,32.250,32.440,32.080,32.225,29.8579,18511200.0,2012-09-24,32.2500,32.440,32.0800,32.2250,29.8579,18511200.0,2012-09-25,32.180,32.2300,31.250,31.30,29.0008,30757800.0
1957,ORCL,2012-12-21,NaN,4.112900e+10,372000000.0,1.464800e+10,NaN,7.965700e+10,4.298300e+10,0.43,4.615000e+09,8.547000e+09,NaN,1.092500e+10,NaN,NaN,2.610000e+08,NaN,1.716600e+10,6.320000e+08,7.331000e+09,1.043100e+10,NaN,881000000.0,1.814000e+09,2.950000e+09,NaN,33.510,33.920,33.200,33.760,31.5181,45601600.0,2012-12-20,34.0900,34.250,33.9300,33.9398,31.6860,28119900.0,2012-12-21,33.510,33.9200,33.200,33.76,31.5181,45601600.0
1958,ORCL,2013-03-22,NaN,4.068600e+10,361000000.0,1.464800e+10,NaN,7.945000e+10,4.334800e+10,0.50,2.498000e+09,8.547000e+09,NaN,5.722000e+09,NaN,NaN,3.500000e+08,NaN,2.623300e+10,6.320000e+08,7.331000e+09,1.043100e+10,NaN,881000000.0,9.220000e+08,1.250000e+09,NaN,32.400,32.500,31.640,31.980,29.8563,64333500.0,2013-03-21,32.7800,32.940,32.1800,32.3000,30.1551,132669500.0,2013-03-22,32.400,32.5000,31.640,31.98,29.8563,64333500.0
1959,ORCL,2013-06-26,NaN,4.002300e+10,438000000.0,1.464800e+10,NaN,7.832700e+10,4.368800e+10,1.99,9.981000e+09,8.547000e+09,NaN,2.341500e+10,NaN,NaN,4.860000e+08,NaN,1.600300e+10,6.320000e+08,7.331000e+09,1.043100e+10,NaN,881000000.0,3.743000e+09,2.950000e+09,NaN,30.190,30.230,29.860,30.140,28.1385,52429800.0,2013-06-25,30.5000,30.530,29.8900,29.9600,27.9704,64051500.0,2013-06-27,30.310,31.1400,30.291,30.45,28.4279,43014900.0
1960,ORCL,2013-09-20,NaN,4.545700e+10,419000000.0,1.464800e+10,NaN,8.640600e+10,4.354100e+10,0.48,2.034000e+09,1.095500e+10,NaN,5.499000e+09,NaN,NaN,1.500000e+08,NaN,8.372000e+09,6.320000e+08,8.871000e+09,1.043100e+10,NaN,881000000.0,8.060000e+08,1.533000e+09,NaN,33.940,34.130,33.670,34.050,31.9110,53470400.0,2013-09-19,33.6400,34.000,33.2500,33.8900,31.7610,63316300.0,2013-09-20,33.940,34.1300,33.670,34.05,31.9110,53470400.0
1961,ORCL,2013-12-20,NaN,4.425200e+10,419000000.0,1.464800e+10,NaN,8.523800e+10,4.464800e+10,0.96,4.744000e+09,1.095500e+10,NaN,1.092500e+10,NaN,NaN,3.020000e+08,NaN,3.987000e+09,6.320000e+08,7.011000e+09,1.043100e+10,NaN,881000000.0,9.300000e+08,1.525000e+09,NaN,36.650,36.795,36.370,36.370,34.2084,40783000.0,2013-12-19,35.5200,36.960,35.5000,36.6000,34.4247,62855300.0,2013-12-20,36.650,36.7950,36.370,36.37,34.2084,40783000.0
1962,ORCL,2014-03-20,NaN,4.169200e+10,396000000.0,1.464800e+10,NaN,8.181200e+10,4.470700e+10,0.53,2.504000e+09,1.095500e+10,NaN,5.740000e+09,NaN,NaN,4.000000e+08,NaN,6.000000e+08,6.320000e+08,6.825000e+09,1.043100e+10,NaN,881000000.0,2.668000e+09,1.516000e+09,NaN,38.500,38.690,38.010,38.370,36.2047,18960200.0,2014-03-19,37.8000,38.960,37.4000,38.5500,36.3745,45154900.0,2014-03-21,38.700,38.8500,37.500,37.50,35.3838,33897900.0
1963,ORCL,2014-06-26,NaN,4.813800e+10,419000000.0,1.464800e+10,NaN,8.181200e+10,4.687800e+10,2.29,1.092500e+10,1.095500e+10,NaN,2.249600e+10,NaN,NaN,5.460000e+08,NaN,3.827500e+10,6.320000e+08,7.430000e+09,1.043100e+10,NaN,881000000.0,3.182000e+09,1.508000e+09,NaN,40.550,40.550,39.980,40.150,37.9979,16642500.0,2014-06-25,40.7300,40.840,40.3900,40.4600,38.2913,13889400.0,2014-06-27,40.030,40.6600,40.030,40.53,38.3576,15320500.0
1964,ORCL,2014-09-23,NaN,5.819400e+10,423000000.0,1.464800e+10,NaN,9.034400e+10,4.735400e+10,0.48,2.191000e+09,1.103700e+10,NaN,5.633000e+09,NaN,NaN,1.600000e+08,NaN,1.266000e+09,6.320000e+08,7.673000e+09,1.043100e+10,NaN,881000000.0,6.910000e+08,1.508000e+09,NaN,39.500,39.590,38.800,38.830,36.8565,34253635.0,2014-09-22,39.6800,39.740,39.2400,39.5800,37.5684,24191139.0,2014-09-24,38.770,39.5560,38.570,39.42,37.4165,18884441.0
1965,ORCL,2014-12-19,NaN,4.813800e+10,490000000.0,1.464800e+10,NaN,9.830500e+10,4.754300e+10,0.56,2.502000e+09,1.103700e+10,NaN,6.056000e+09,NaN,NaN,3.020000e+08,NaN,9.275000e+09,6.320000e+08,7.224000e+09,1.043100e+10,NaN,881000000.0,7.640000e+08,1.508000e+09,NaN,45.100,46.150,44.980,46.000,43.7962,41782191.0,2014-12-18,43.8300,45.370,43.5700,45.3500,43.1773,54491326.0,2014-12-19,45.100,46.1500,44.980,46.00,43.7962,41782191.0
1966,ORCL,2015-03-19,NaN,5.129400e+10,471000000.0,1.464800e+10,NaN,9.034400e+10,4.687800e+10,0.57,2.495000e+09,1.103700e+10,NaN,5.944000e+09,NaN,NaN,4.520000e+08,NaN,9.334000e+09,6.320000e+08,6.878000e+09,1.043100e+10,NaN,881000000.0,7.240000e+08,1.999000e+09,NaN,44.000,44.490,44.000,44.160,42.1601,15729627.0,2015-03-18,44.3000,44.935,43.3500,44.1300,42.1314,37896791.0,2015-03-20,44.130,44.7300,44.060,44.41,42.3988,20724698.0
1967,ORCL,2015-06-25,NaN,4.812800e+10,471000000.0,1.464800e+10,NaN,9.026600e+10,4.866300e+10,2.42,1.095500e+10,1.103700e+10,NaN,2.249600e+10,NaN,NaN,6.080000e+08,NaN,1.680900e+10,6.320000e+08,7.673000e+09,1.043100e+10,NaN,881000000.0,2.954000e+09,1.508000e+09,NaN,41.240,41.470,41.055,41.060,39.3384,13547448.0,2015-06-24,41.5400,41.770,41.2000,41.2000,39.4726,17768033.0,2015-06-26,41.100,41.3700,40.970,40.99,39.2714,39685430.0
1968,ORCL,2015-09-18,NaN,6.212200e+10,422000000.0,1.464800e+10,NaN,1.097060e+11,4.709700e+10,0.40,2.184000e+09,9.938000e+09,NaN,5.794000e+09,NaN,NaN,2.190000e+08,NaN,1.166000e+09,7.440000e+08,7.638000e+09,1.043100e+10,NaN,881000000.0,6.910000e+08,2.000000e+09,NaN,36.290,36.980,36.260,36.380,34.9849,34919765.0,2015-09-17,36.7400,37.670,36.5000,36.7400,35.3311,37298982.0,2015-09-18,36.290,36.9800,36.260,36.38,34.9849,34919765.0
1969,ORCL,2015-12-18,NaN,6.252000e+10,415000000.0,1.464800e+10,NaN,1.064830e+11,4.592400e+10,0.57,2.197000e+09,9.938000e+09,NaN,1.183200e+10,NaN,NaN,3.240000e+08,NaN,8.996000e+09,7.440000e+08,7.461000e+09,1.043100e+10,NaN,881000000.0,6.900000e+08,1.999000e+09,NaN,36.890,37.080,36.310,36.350,35.0937,28648184.0,2015-12-17,38.0900,38.200,36.5400,36.9300,35.6536,42879939.0,2015-12-18,36.890,37.0800,36.310,36.35,35.0937,28648184.0
1970,ORCL,2016-03-18,NaN,6.252000e+10,410000000.0,1.464800e+10,NaN,1.109030e+11,4.587000e+10,0.57,2.142000e+09,9.938000e+09,NaN,1.781700e+10,NaN,NaN,6.430000e+08,NaN,9.327000e+09,7.440000e+08,7.638000e+09,1.043100e+10,NaN,881000000.0,6.570000e+08,1.999000e+09,NaN,40.870,41.490,40.650,41.480,40.2144,34354028.0,2016-03-17,40.1500,40.960,40.0700,40.6100,39.3709,22160775.0,2016-03-18,40.870,41.4900,40.650,41.48,40.2144,34354028.0
1971,ORCL,2016-06-22,NaN,6.252000e+10,504000000.0,1.464800e+10,NaN,1.109030e+11,4.866300e+10,2.26,1.095500e+10,9.938000e+09,NaN,2.444300e+10,NaN,NaN,7.120000e+08,NaN,2.388000e+09,7.440000e+08,8.191000e+09,1.043100e+10,NaN,881000000.0,2.751000e+09,3.750000e+09,NaN,40.150,40.340,39.870,40.010,38.9332,12643366.0,2016-06-21,39.9300,40.120,39.7475,39.9900,38.9137,20111116.0,2016-06-23,40.400,40.8700,40.260,40.83,39.7311,15428483.0
1972,ORCL,2016-09-19,NaN,6.431300e+10,504000000.0,1.464800e+10,NaN,1.121800e+11,4.728900e+10,0.40,1.747000e+09,9.453000e+09,NaN,5.794000e+09,NaN,NaN,2.190000e+08,NaN,8.451000e+09,7.440000e+08,8.191000e+09,1.043100e+10,NaN,881000000.0,7.110000e+08,3.750000e+09,NaN,39.130,39.550,39.045,39.230,38.3143,19801878.0,2016-09-19,39.1300,39.550,39.0450,39.2300,38.3143,19801878.0,2016-09-20,39.550,39.6000,39.055,39.07,38.1580,12119101.0
1973,ORCL,2016-12-19,NaN,6.431300e+10,504000000.0,1.464800e+10,NaN,1.121800e+11,4.728900e+10,0.92,3.945000e+09,9.453000e+09,NaN,1.183200e+10,NaN,NaN,4.290000e+08,NaN,1.744700e+10,7.440000e+08,8.191000e+09,1.043100e+10,NaN,881000000.0,1.401000e+09,3.750000e+09,NaN,39.030,39.190,38.590,38.900,38.1392,15134543.0,2016-12-19,39.0300,39.190,38.5900,38.9000,38.1392,15134543.0,2016-12-20,38.960,39.1100,38.800,39.00,38.2373,14006387.0
1974,ORCL,2017-03-17,NaN,6.431300e+10,504000000.0,1.464800e+10,NaN,1.121800e+11,4.728900e+10,1.43,6.087000e+09,9.453000e+09,NaN,1.781700e+10,NaN,NaN,6.430000e+08,NaN,2.646100e+10,7.440000e+08,8.191000e+09,1.586900e+10,NaN,881000000.0,2.058000e+09,3.750000e+09,NaN,45.250,45.980,45.110,45.660,44.9412,31688720.0,2017-03-16,46.3900,46.990,45.6500,45.7300,45.0101,67535437.0,2017-03-17,45.250,45.9800,45.110,45.66,44.9412,31688720.0
1975,ORCL,2017-06-27,NaN,6.431300e+10,504000000.0,1.464800e+10,NaN,1.121800e+11,4.728900e+10,2.26,9.938000e+09,9.453000e+09,NaN,2.435500e+10,NaN,NaN,7.120000e+08,NaN,1.432800e+10,7.440000e+08,8.191000e+09,2.370900e+10,NaN,881000000.0,2.929000e+09,3.750000e+09,NaN,50.750,51.450,50.520,50.750,50.1668,17801028.0,2017-06-26,50.9900,51.700,50.7700,50.8600,50.2755,29327595.0,2017-06-28,51.070,51.0900,50.810,50.87,50.2854,15431884.0
1976,ORCL,2017-09-18,NaN,7.451500e+10,599000000.0,1.464800e+10,NaN,1.349910e+11,5.386000e+10,0.44,1.832000e+09,7.622000e+09,NaN,5.954000e+09,NaN,NaN,2.220000e+08,NaN,8.613000e+09,7.726667e+08,8.835000e+09,5.110000e+09,NaN,881000000.0,6.950000e+08,9.797000e+09,NaN,48.880,49.060,48.090,48.330,47.9546,29416689.0,2017-09-18,48.8800,49.060,48.0900,48.3300,47.9546,29416689.0,2017-09-19,48.490,48.5000,47.880,48.04,47.6668,22712871.0
1977,ORCL,2017-12-18,NaN,7.451500e+10,599000000.0,1.464800e+10,NaN,1.349910e+11,5.386000e+10,0.94,3.864000e+09,5.791000e+09,NaN,1.195200e+10,NaN,NaN,4.630000e+08,NaN,1.768300e+10,8.013333e+08,8.835000e+09,1.061800e+10,NaN,881000000.0,1.393000e+09,9.797000e+09,NaN,48.530,48.850,47.680,47.710,47.5259,24690916.0,2017-12-18,48.5300,48.850,47.6800,47.7100,47.5259,24690916.0,2017-12-19,47.985,48.3500,47.740,47.82,47.6355,28137680.0
1978,ORCL,2018-03-21,NaN,7.451500e+10,599000000.0,1.464800e+10,NaN,1.349910e+11,5.386000e+10,1.49,6.103000e+09,3.960000e+09,NaN,1.819900e+10,NaN,NaN,7.220000e+08,NaN,2.695700e+10,8.300000e+08,8.835000e+09,1.620200e+10,NaN,881000000.0,2.073000e+09,9.797000e+09,NaN,47.290,48.060,47.010,47.020,47.0200,34595470.0,2018-03-20,46.8000,47.750,46.4300,47.0500,47.0500,68331479.0,2018-03-22,46.720,47.0215,46.110,46.42,46.4200,9570792.0
1979,ORCL,2018-06-22,NaN,7.451500e+10,599000000.0,1.464800e+10,NaN,1.349910e+11,5.386000e+10,2.11,8.901000e+09,3.960000e+09,NaN,2.444300e+10,NaN,NaN,8.710000e+08,NaN,1.343500e+10,8.300000e+08,8.835000e+09,2.241000e+10,NaN,881000000.0,2.751000e+09,3.750000e+09,NaN,43.200,44.300,43.160,44.100,43.9278,30594322.0,2018-06-21,43.1800,43.840,42.9800,43.1000,42.9317,32635062.0,2018-06-22,43.200,44.3000,43.160,44.10,43.9278,30594322.0
1980,ORCL,2018-09-19,NaN,7.615900e+10,529000000.0,1.464800e+10,NaN,1.378510e+11,4.637200e+10,0.52,2.144000e+09,3.110000e+08,NaN,6.355000e+09,NaN,NaN,2.850000e+08,NaN,5.331000e+09,8.680000e+08,6.288000e+09,5.432000e+09,NaN,881000000.0,1.160000e+08,4.491000e+09,NaN,48.920,49.540,48.660,49.430,49.0389,20904826.0,2018-09-18,47.5100,49.540,47.3600,49.0300,48.6421,33451106.0,2018-09-20,49.660,51.0750,49.560,50.43,50.0310,26973480.0
1981,ORCL,2018-12-19,NaN,7.615900e+10,529000000.0,1.464800e+10,NaN,1.378510e+11,4.637200e+10,1.05,4.358000e+09,3.110000e+08,NaN,1.290400e+10,NaN,NaN,5.730000e+08,NaN,5.331000e+09,8.680000e+08,6.288000e+09,1.043100e+10,NaN,881000000.0,1.160000e+08,4.491000e+09,NaN,46.060,47.440,45.750,46.450,46.2683,34397250.0,2018-12-18,48.1000,48.340,45.4400,45.8500,45.6706,42855600.0,2018-12-20,46.050,46.9500,45.480,46.24,46.0591,35165179.0
1982,ORCL,2019-03-18,NaN,7.615900e+10,529000000.0,1.464800e+10,NaN,1.378510e+11,4.637200e+10,0.07,3.110000e+08,3.110000e+08,NaN,1.926600e+10,NaN,NaN,8.780000e+08,NaN,5.331000e+09,8.680000e+08,6.288000e+09,1.043100e+10,NaN,881000000.0,1.160000e+08,4.491000e+09,NaN,52.870,53.960,52.780,53.460,53.4600,21953604.0,2019-03-18,52.8700,53.960,52.7800,53.4600,53.4600,21953604.0,2019-03-19,53.800,54.3750,53.750,54.04,54.0400,19214018.0
1983,ORCL,2019-06-21,NaN,7.615900e+10,529000000.0,1.464800e+10,NaN,1.378510e+11,4.637200e+10,2.30,9.452000e+09,1.123500e+10,NaN,2.487900e+10,NaN,NaN,1.000000e+09,NaN,3.779200e+10,8.680000e+08,6.288000e+09,1.043100e+10,NaN,881000000.0,1.160000e+08,2.500000e+09,NaN,57.140,57.150,56.060,56.120,56.1200,45168973.0,2019-06-20,55.9800,57.470,55.5300,56.9900,56.9900,54173900.0,2019-06-21,57.140,57.1500,56.060,56.12,56.1200,45168973.0

Last choice, I think: do I fill in the remaining NaN's with zero, or some other dummy constant, to make the ML happy later? Is there a better way to deal with some companies reporting data and others not?